-- ============================================================================
-- Anvaya Supabase SQL Editor part 01 of 05
-- Run the files in db/sql_editor_parts in numeric order, one at a time.
-- This file is generated by concatenating the ordered migrations listed below.
-- It is idempotent: if a part fails after partially running, fix the error and
-- re-run the same part before continuing to the next number.
--
-- Includes:
--   - db/migrations/0001_schemas_and_helpers.sql
--   - db/migrations/0002_enums.sql
--   - db/migrations/0003_identity.sql
--   - db/migrations/0004_doctor_access.sql
--   - db/migrations/0005_consent.sql
-- ============================================================================

-- >>> BEGIN db/migrations/0001_schemas_and_helpers.sql
-- ============================================================================
-- Anvaya / Rxanvaya — Supabase migration 0001
-- Schemas, shared helper functions, updated_at / immutability triggers
-- ----------------------------------------------------------------------------
-- Purpose   : Create the `anvaya` schema for privileged (non-PostgREST-exposed)
--             helpers, and the generic trigger functions reused by later
--             migrations.
-- Depends on: nothing
-- Fresh safe: YES (all objects created IF NOT EXISTS / OR REPLACE)
-- Contract  : adds new objects only; changes no existing application contract
--
-- SECURITY NOTE
--   Supabase's PostgREST exposes the schemas listed in `pgrst.db_schemas`
--   (default: `public, graphql_public`). All data tables live in `public` so the
--   Next.js app can reach them with the anon key + RLS. Every *privileged*
--   function (hard delete, audit writer, deterministic classification,
--   correction submission) lives in `anvaya`, which is NOT exposed, so the
--   browser can never RPC into it directly.
--
-- EXTENSIONS
--   Deliberately NONE. This schema needs no pgcrypto / citext / pgvector:
--     * gen_random_uuid()  -> built in since PostgreSQL 13
--     * sha256()           -> built in since PostgreSQL 11
--   That keeps the migration runnable on a brand-new Supabase project with no
--   extension provisioning step and no superuser action.
-- ============================================================================

create schema if not exists anvaya;

comment on schema anvaya is
  'Privileged helper functions for the Anvaya pipeline. Intentionally NOT added to pgrst.db_schemas so the frontend cannot invoke these directly.';

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'Generic BEFORE UPDATE trigger: keeps updated_at truthful. Applied only to mutable tables.';

-- ---------------------------------------------------------------------------
-- Append-only / immutable guard
-- ---------------------------------------------------------------------------
create or replace function public.guard_immutable_row()
returns trigger
language plpgsql
as $$
declare
  v_id text;
begin
  -- In a row-level trigger NEW/OLD are composite records, not jsonb, so the
  -- record has to be converted before a field can be read by name.
  if tg_op = 'DELETE' then
    v_id := to_jsonb(old) ->> 'id';
  else
    v_id := to_jsonb(new) ->> 'id';
  end if;

  -- UPDATE is refused unconditionally: history is never rewritten.
  -- DELETE is refused too, with one narrow exception — a sanctioned erasure.
  -- anvaya.hard_delete_report() / hard_delete_patient() set this
  -- transaction-local flag, which is how a patient's right to erasure can be
  -- honoured without making these tables editable in normal operation.
  -- The flag can only be set by a SECURITY DEFINER function; a client session
  -- has no way to set another backend's GUC.
  if tg_op = 'DELETE' and current_setting('anvaya.erasure_in_progress', true) = 'on' then
    return old;
  end if;

  raise exception 'anvaya: % is append-only and cannot be % (row %)',
    tg_table_name, lower(tg_op), coalesce(v_id, '?');
end;
$$;

comment on function public.guard_immutable_row() is
  'BEFORE UPDATE OR DELETE trigger that hard-blocks mutation. Used on deterministic validation output, AI generations and audit records so no client (and no LLM write-back path) can rewrite history.';

-- ---------------------------------------------------------------------------
-- Small numeric helpers used by checks / classification
-- ---------------------------------------------------------------------------
create or replace function anvaya.num_nonnulls(variadic anyarray)
returns int
language sql
immutable
as $$
  select count(*)::int from unnest($1) as v(x) where x is not null;
$$;

comment on function anvaya.num_nonnulls(anyarray) is
  'Portable "exactly one of these FKs is set" helper for polymorphic subject columns.';

-- <<< END db/migrations/0001_schemas_and_helpers.sql

-- >>> BEGIN db/migrations/0002_enums.sql
-- ============================================================================
-- Anvaya / Rxanvaya — Supabase migration 0002
-- Enum types
-- ----------------------------------------------------------------------------
-- Purpose   : Every closed vocabulary used by the application, defined once.
-- Depends on: 0001
-- Fresh safe: YES (guarded by pg_type lookups; PostgreSQL has no
--             "CREATE TYPE IF NOT EXISTS")
-- Contract  : Enum members are copied VERBATIM from src/lib/data.ts and
--             src/lib/i18n.tsx. Do not silently add or remove members — the
--             TypeScript unions are the existing contract.
--
--   src/lib/data.ts:7   type LangCode = "en" | "hi" | "bn"
--   src/lib/data.ts:8   type Status   = "normal" | "borderline" | "high" | "low" | "critical"
--   src/lib/i18n.tsx:16 type ReadingMode = "standard" | "simple" | "very"
--   src/lib/data.ts     conf.level: "high" | "moderate"   (only these two occur)
--   src/app/api/answer/route.ts  confidence: "high" | "moderate"
--   src/components/voice.tsx / api/answer  direction: "up" | "down" | "flat"
-- ============================================================================

do $do$
begin
  -- language -----------------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_lang_code') then
    create type anvaya_lang_code as enum ('en', 'hi', 'bn');
  end if;

  -- deterministic result classification --------------------------------------
  -- NOTE: the task brief mentions Low/Normal/High/Critical, but the shipped
  -- application has FIVE states and renders "borderline" as "Needs attention"
  -- (src/lib/i18n.tsx "status.borderline"). The enum therefore keeps all five.
  if not exists (select 1 from pg_type where typname = 'anvaya_test_status') then
    create type anvaya_test_status as enum ('normal', 'borderline', 'high', 'low', 'critical');
  end if;

  -- reading level ------------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_reading_level') then
    create type anvaya_reading_level as enum ('standard', 'simple', 'very');
  end if;

  -- confidence / trust -------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_confidence_level') then
    create type anvaya_confidence_level as enum ('high', 'moderate');
  end if;

  -- trend direction ----------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_trend_dir') then
    create type anvaya_trend_dir as enum ('up', 'down', 'flat');
  end if;

  -- roles --------------------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_role') then
    create type anvaya_role as enum ('patient', 'doctor', 'admin');
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_account_status') then
    create type anvaya_account_status as enum ('active', 'suspended', 'closed');
  end if;

  -- consent ------------------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_consent_status') then
    create type anvaya_consent_status as enum ('granted', 'withdrawn', 'expired', 'declined');
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_consent_purpose') then
    create type anvaya_consent_purpose as enum (
      'report_parsing',      -- OCR + structured extraction of the uploaded report
      'ai_explanation',      -- anonymised data sent to the LLM for plain-language text
      'rag_grounding',       -- retrieval over the guideline corpus
      'voice_interaction',   -- STT/TTS and voice Q&A
      'longitudinal_trends', -- comparing against the patient's own earlier reports
      'doctor_review'        -- sharing with a reviewing clinician
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_consent_channel') then
    create type anvaya_consent_channel as enum ('in_app', 'voice', 'clinic', 'paper', 'imported');
  end if;

  -- report lifecycle ---------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_report_status') then
    create type anvaya_report_status as enum (
      'uploaded',        -- file received, nothing run yet
      'processing',      -- a job is running
      'extracted',       -- structured results present, awaiting patient confirmation
      'analysed',        -- validated + explained
      'in_review',       -- with a clinician
      'released',        -- doctor-signed and patient-facing
      'failed'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_upload_channel') then
    -- src/app/upload/page.tsx offers: camera (/scan), file (PDF/JPG/PNG/CSV) and
    -- a "manual entry" sheet. "sample" is the bundled demo report.
    create type anvaya_upload_channel as enum ('camera', 'file', 'csv', 'manual', 'sample');
  end if;

  -- processing jobs ----------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_job_status') then
    create type anvaya_job_status as enum ('queued', 'running', 'succeeded', 'failed', 'cancelled');
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_job_stage') then
    -- Superset of the 5 friendly labels in src/lib/i18n.tsx (process.s1..s5),
    -- extended with the stages the architecture document requires.
    create type anvaya_job_stage as enum (
      'ocr',            -- process.s1 "Reading the report"
      'parsing',        -- process.s2 "Identifying your test results"
      'normalisation',  -- unit/synonym standardisation
      'validation',     -- process.s3 "Checking normal ranges"
      'anonymisation',  -- PII strip before any external call
      'rag',            -- retrieval
      'explanation',    -- process.s4 + s5 "Finding patterns" / "Preparing a simple explanation"
      'review',
      'release'
    );
  end if;

  -- provenance ---------------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_value_source') then
    create type anvaya_value_source as enum (
      'ocr',
      'csv_import',
      'manual_entry',
      'patient_correction',
      'doctor_correction'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_range_origin') then
    -- PIPELINE in src/lib/data.ts: "Your lab's own printed ranges are used —
    -- not generic internet numbers." So the printed range is a first-class
    -- origin alongside the curated ICMR/WHO catalogue.
    create type anvaya_range_origin as enum ('lab_printed', 'catalogue');
  end if;

  -- review workflow ----------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_review_status') then
    create type anvaya_review_status as enum (
      'draft',
      'pending_review',
      'needs_edit',
      'approved',
      'released',
      'withdrawn'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_version_origin') then
    create type anvaya_version_origin as enum ('ai_draft', 'doctor_edit', 'reissue');
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_text_author') then
    create type anvaya_text_author as enum ('ai', 'doctor', 'human_editor');
  end if;

  -- AI generation ------------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_generation_purpose') then
    create type anvaya_generation_purpose as enum (
      'test_explanation',
      'pattern_insight',
      'report_summary',
      'qa_answer',
      'translation'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_generation_status') then
    create type anvaya_generation_status as enum ('queued', 'running', 'succeeded', 'failed', 'blocked');
  end if;

  -- Q&A ----------------------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_message_role') then
    create type anvaya_message_role as enum ('user', 'assistant');
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_qa_channel') then
    -- src/app/ask/page.tsx has a text input and a voice sheet.
    create type anvaya_qa_channel as enum ('text', 'voice');
  end if;

  -- storage / files ----------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_file_kind') then
    create type anvaya_file_kind as enum (
      'original',        -- as-uploaded photo / PDF
      'processed_image', -- deskewed / contrast-fixed render
      'ocr_artifact',    -- OCR engine output blob, if retained
      'pdf_export',      -- patient or doctor PDF
      'tts_audio'        -- generated narration
    );
  end if;

  -- deletion -----------------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_deletion_scope') then
    create type anvaya_deletion_scope as enum ('single_report', 'all_reports', 'account');
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_deletion_status') then
    create type anvaya_deletion_status as enum ('requested', 'in_progress', 'completed', 'rejected', 'failed');
  end if;

  -- errors -------------------------------------------------------------------
  if not exists (select 1 from pg_type where typname = 'anvaya_severity') then
    create type anvaya_severity as enum ('debug', 'info', 'warning', 'error', 'critical');
  end if;

  if not exists (select 1 from pg_type where typname = 'anvaya_component') then
    create type anvaya_component as enum (
      'api', 'storage', 'ocr', 'parser', 'validator', 'anonymiser', 'rag', 'llm', 'tts', 'stt', 'database', 'other'
    );
  end if;

end
$do$;

comment on type anvaya_test_status is
  'Deterministic rule-engine output only. NEVER written by the LLM. Source of truth lives in public.validation_results; this enum is reused for denormalised display copies.';

-- <<< END db/migrations/0002_enums.sql

-- >>> BEGIN db/migrations/0003_identity.sql
-- ============================================================================
-- Anvaya / Rxanvaya — Supabase migration 0003
-- Identity: profiles, patients, doctors
-- ----------------------------------------------------------------------------
-- Purpose   : Separate the *auth-facing* row (profiles) from the two
--             role-specific records. Patient PII is confined to `patients`;
--             everything downstream that is read by the UI joins through
--             `patients` only when identity is genuinely needed.
-- Depends on: 0001 schemas/helpers, 0002 enums
-- Fresh safe: YES
-- Contract  : NEW. The current codebase has no auth at all — src/lib/data.ts
--             hardcodes a single fictional PATIENT object and there is no
--             login/middleware/session code anywhere in src/. This migration
--             introduces the identity model the architecture requires; it
--             removes nothing.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- profiles — 1:1 with auth.users
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id            uuid primary key,                       -- == auth.users.id
  role          anvaya_role        not null default 'patient',
  status        anvaya_account_status not null default 'active',
  full_name     text,
  email         text,
  preferred_language anvaya_lang_code not null default 'en',
  last_seen_at  timestamptz,
  created_at    timestamptz        not null default now(),
  updated_at    timestamptz        not null default now(),

  constraint profiles_email_lower_chk check (email is null or email = lower(email))
);

comment on table public.profiles is
  'One row per auth.users row. Holds ONLY routing/identity metadata — no clinical data and no PII beyond name/email needed for sign-in display.';
comment on column public.profiles.role is
  'Drives every RLS policy. patient | doctor | admin. Set by the backend/service role, never by the client.';

create unique index if not exists profiles_email_key on public.profiles (lower(email)) where email is not null;
create index if not exists profiles_role_idx on public.profiles (role) where status = 'active';

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- patients — the PII record
-- ---------------------------------------------------------------------------
create table if not exists public.patients (
  id                uuid primary key default gen_random_uuid(),
  profile_id        uuid unique,                        -- nullable: clinic-entered patients may not have a login yet
  full_name         text        not null,
  name_local_script text,                               -- e.g. Devanagari rendering, mirrors data.ts PATIENT.name.hi
  date_of_birth     date,
  sex               text        check (sex is null or sex in ('female', 'male', 'other', 'unspecified')),
  phone             text,
  email             text,
  city              text,
  state             text,
  preferred_language anvaya_lang_code not null default 'en',
  -- Accessibility settings. NOTE: the shipped app keeps these in localStorage
  -- (src/lib/i18n.tsx:552-563 under LS_KEY). They are mirrored here so a
  -- returning patient keeps them across devices; the client may still treat
  -- localStorage as the fast path.
  reading_level     anvaya_reading_level not null default 'standard',
  voice_enabled     boolean     not null default true,
  high_contrast     boolean     not null default false,
  reduce_motion     boolean     not null default false,
  font_scale        smallint    not null default 0 check (font_scale between 0 and 2),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,

  constraint patients_fk_profile foreign key (profile_id)
    references public.profiles (id) on delete set null,
  constraint patients_font_scale_chk check (font_scale >= 0 and font_scale <= 2)
);

comment on table public.patients is
  'PHI ZONE. Identifiable demographics. Never referenced by any AI/RAG table; the pipeline reaches the model only through public.anonymization_records.';
comment on column public.patients.name_local_script is
  'Backs the L2 {en, hi} name pattern in src/lib/data.ts (PATIENT.name).';

create index if not exists patients_profile_idx on public.patients (profile_id);
create index if not exists patients_active_idx on public.patients (full_name) where deleted_at is null;

drop trigger if exists patients_set_updated_at on public.patients;
create trigger patients_set_updated_at
  before update on public.patients
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- doctors
-- ---------------------------------------------------------------------------
create table if not exists public.doctors (
  id              uuid primary key default gen_random_uuid(),
  profile_id      uuid unique not null,
  full_name       text        not null,
  registration_no text,                                 -- medical council registration
  registration_body text,
  specialty       text,
  institution     text,
  verified        boolean     not null default false,
  verified_at     timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint doctors_fk_profile foreign key (profile_id)
    references public.profiles (id) on delete cascade
);

comment on table public.doctors is
  'Reviewer identity. Registration details are what make a sign-off attributable and auditable.';

create unique index if not exists doctors_registration_key
  on public.doctors (registration_body, registration_no)
  where registration_no is not null;

drop trigger if exists doctors_set_updated_at on public.doctors;
create trigger doctors_set_updated_at
  before update on public.doctors
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Keep profiles in sync with auth.users
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, role, full_name, email)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'role', ''), 'patient')::anvaya_role,
    new.raw_user_meta_data ->> 'full_name',
    new.email
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

comment on function public.handle_new_auth_user() is
  'Creates the profile row on signup. SECURITY DEFINER so it can write profiles despite the no-client-INSERT policy. Role is taken from server-set user metadata, never from client-controlled input.';

-- Installed only when auth.users exists (always true on Supabase; skipped in
-- bare-Postgres test harnesses) so the file stays runnable in both.
do $do$
begin
  if to_regclass('auth.users') is not null then
    drop trigger if exists on_auth_user_created on auth.users;
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute function public.handle_new_auth_user();
  end if;
end
$do$;

-- <<< END db/migrations/0003_identity.sql

-- >>> BEGIN db/migrations/0004_doctor_access.sql
-- ============================================================================
-- Anvaya / Rxanvaya — Supabase migration 0004
-- Doctor ↔ patient authorisation grants
-- ----------------------------------------------------------------------------
-- Purpose   : A clinician may only see reports for patients they have been
--             explicitly granted. This table is the single predicate behind
--             every doctor-facing RLS policy, so "cannot arbitrarily access
--             unrelated patients" is enforced in the database rather than in
--             application code.
-- Depends on: 0003
-- Fresh safe: YES
-- Contract  : NEW. The current app has no doctor login at all — /doctor is a
--             patient-facing printable summary (src/app/doctor/page.tsx renders
--             "A clinician-style view to share with your doctor"). Introducing a
--             real reviewer identity does not change that page's contract.
-- ============================================================================

create table if not exists public.doctor_patient_access (
  id          uuid primary key default gen_random_uuid(),
  doctor_id   uuid not null,
  patient_id  uuid not null,
  status      text not null default 'active'
              check (status in ('active', 'revoked')),
  reason      text,                                     -- why access was granted (audit narrative)
  granted_by  uuid,                                     -- profiles.id of whoever authorised it
  granted_at  timestamptz not null default now(),
  expires_at  timestamptz,
  revoked_at  timestamptz,
  revoked_by  uuid,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  constraint dpa_fk_doctor  foreign key (doctor_id)  references public.doctors (id) on delete cascade,
  constraint dpa_fk_patient foreign key (patient_id) references public.patients (id) on delete cascade,
  constraint dpa_fk_granted_by foreign key (granted_by) references public.profiles (id) on delete set null,
  constraint dpa_revoked_consistency check (
    (status <> 'revoked') or (revoked_at is not null)
  ),
  constraint dpa_expiry_after_grant check (expires_at is null or expires_at > granted_at)
);

comment on table public.doctor_patient_access is
  'Time-boxed reviewer authorisation. Access is deny-by-default: no row, no visibility.';

-- One ACTIVE grant per (doctor, patient); history of revoked grants is kept.
create unique index if not exists dpa_one_active_per_pair
  on public.doctor_patient_access (doctor_id, patient_id)
  where status = 'active';

create index if not exists dpa_patient_idx on public.doctor_patient_access (patient_id, status);
create index if not exists dpa_doctor_active_idx on public.doctor_patient_access (doctor_id) where status = 'active';

drop trigger if exists dpa_set_updated_at on public.doctor_patient_access;
create trigger dpa_set_updated_at
  before update on public.doctor_patient_access
  for each row execute function public.set_updated_at();

-- <<< END db/migrations/0004_doctor_access.sql

-- >>> BEGIN db/migrations/0005_consent.sql
-- ============================================================================
-- Anvaya / Rxanvaya — Supabase migration 0005
-- Consent: policy catalogue + patient consent records
-- ----------------------------------------------------------------------------
-- Purpose   : Auditable, purpose-scoped, versioned consent. A boolean
--             consent=true is NOT sufficient: the record must say which policy
--             text was shown, for what purpose, when, via what channel, and
--             when it was withdrawn.
-- Depends on: 0002, 0003
-- Fresh safe: YES
-- Contract  : NEW. The shipped app has no consent UI and no consent storage —
--             src/app/settings/page.tsx has language/reading-mode/font/voice/
--             contrast/motion controls only, and the only privacy text is
--             src/app/how/page.tsx:117-120 ("Reports can be deleted after
--             processing"). This table is what turns that claim into a record.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- consent_policies — the versioned text a patient actually agreed to
-- ---------------------------------------------------------------------------
create table if not exists public.consent_policies (
  id             uuid primary key default gen_random_uuid(),
  code           text        not null,                  -- stable policy family, e.g. 'anvaya_processing'
  version        text        not null,                  -- e.g. '1.0.0'
  purpose        anvaya_consent_purpose not null,
  title_en       text        not null,
  title_hi       text,
  summary_en     text        not null,
  summary_hi     text,
  full_text_en   text        not null,
  full_text_hi   text,
  doc_hash       text        not null,                  -- sha256 of the canonical text shown
  effective_from timestamptz not null default now(),
  effective_to   timestamptz,
  is_active      boolean     not null default true,

  constraint consent_policies_version_key unique (code, version, purpose),
  constraint consent_policies_window_chk check (effective_to is null or effective_to > effective_from)
);

comment on table public.consent_policies is
  'Immutable catalogue of consent texts. Versioning here is what lets an old consent remain valid under the policy that was current when it was given.';
comment on column public.consent_policies.doc_hash is
  'sha256 of the exact text rendered to the patient. Makes "what did they actually agree to?" answerable years later.';

-- Exactly one active version per (code, purpose).
create unique index if not exists consent_policies_one_active
  on public.consent_policies (code, purpose)
  where is_active;

create index if not exists consent_policies_purpose_idx on public.consent_policies (purpose) where is_active;

-- ---------------------------------------------------------------------------
-- patient_consents — one row per decision (append-oriented)
-- ---------------------------------------------------------------------------
create table if not exists public.patient_consents (
  id            uuid primary key default gen_random_uuid(),
  patient_id    uuid not null,
  policy_id     uuid not null,
  purpose       anvaya_consent_purpose not null,
  status        anvaya_consent_status not null,
  channel       anvaya_consent_channel not null default 'in_app',
  granted_at    timestamptz not null default now(),
  expires_at    timestamptz,
  revoked_at    timestamptz,
  revoked_by    uuid,
  revocation_reason text,
  -- Evidence bundle: ip, user agent, UI version, STT transcript reference for
  -- voice consent. Deliberately jsonb (free-form evidence) — the *queryable*
  -- facts (who/what/when) are proper columns above.
  evidence      jsonb not null default '{}'::jsonb,
  ip_address    inet,
  user_agent    text,
  created_at    timestamptz not null default now(),

  constraint consents_fk_patient foreign key (patient_id) references public.patients (id) on delete restrict,
  constraint consents_fk_policy  foreign key (policy_id)  references public.consent_policies (id) on delete restrict,
  constraint consents_fk_revoked_by foreign key (revoked_by) references public.profiles (id) on delete set null,
  -- A consent can only be "revoked" with a timestamp, and only if it was granted.
  constraint consents_revoked_needs_ts check (status <> 'withdrawn' or revoked_at is not null),
  constraint consents_declined_not_granted check (status <> 'declined' or revoked_at is null)
);

comment on table public.patient_consents is
  'Append-oriented consent ledger. A withdrawal is a NEW row (status withdrawn, with revoked_at), never a delete or an edit, so the original grant stays provable.';
comment on constraint consents_fk_patient on public.patient_consents is
  'ON DELETE RESTRICT, deliberately not CASCADE. A patient row must never silently take the consent ledger with it: erasure goes through anvaya.hard_delete_patient(), which deletes consents explicitly inside a sanctioned-erasure window and keeps an audit record that it did so. RESTRICT also avoids a confusing failure mode — because row triggers fire before FK enforcement, a CASCADE here would surface the append-only error instead of the referential one.';
comment on column public.patient_consents.purpose is
  'Denormalised from consent_policies.purpose so the common "is purpose X consented right now?" query is a single indexed lookup.';

-- NOTE: deliberately NO unique index on (patient_id, purpose) WHERE status =
-- 'granted'. Because this table is append-only (the immutable trigger below
-- forbids flipping an old row to 'withdrawn'), a patient who withdraws and later
-- re-consents would legitimately hold two 'granted' rows. Authority is therefore
-- "the most recent row for this purpose wins" — implemented in
-- anvaya.has_active_consent() (0017). A unique index here would make lawful
-- re-consent impossible.
create index if not exists consents_active_lookup_idx
  on public.patient_consents (patient_id, purpose, granted_at desc);

create index if not exists consents_patient_idx on public.patient_consents (patient_id, granted_at desc);
create index if not exists consents_policy_idx on public.patient_consents (policy_id);

-- Append-only: no UPDATE, no DELETE. Corrections are new rows.
drop trigger if exists consents_immutable on public.patient_consents;
create trigger consents_immutable
  before update or delete on public.patient_consents
  for each row execute function public.guard_immutable_row();

-- <<< END db/migrations/0005_consent.sql
