-- ============================================================================
-- Anvaya Supabase SQL Editor part 03 of 05
-- Run the files in db/sql_editor_parts in numeric order, one at a time.
-- This file is generated by concatenating the ordered migrations listed below.
-- It is idempotent: if a part fails after partially running, fix the error and
-- re-run the same part before continuing to the next number.
--
-- Includes:
--   - db/migrations/0011_rag.sql
--   - db/migrations/0012_ai.sql
--   - db/migrations/0013_patterns.sql
--   - db/migrations/0014_review_release.sql
--   - db/migrations/0015_qa_voice.sql
--   - db/migrations/0016_audit_deletion_errors.sql
--   - db/migrations/0017_functions.sql
-- ============================================================================

-- >>> BEGIN db/migrations/0011_rag.sql
-- ============================================================================
-- Anvaya / RxAnvaya — Supabase migration 0011
-- RAG metadata: sources, documents, chunks, retrievals, matches
-- ----------------------------------------------------------------------------
-- Purpose   : Persist enough metadata to answer "what source supported this
--             statement?" durably, while the vector index itself stays in the
--             self-hosted FAISS store.
-- Depends on: 0001, 0002
-- Fresh safe: YES
-- Contract  : rag_sources maps 1:1 onto the Source interface in
--             src/lib/data.ts:629-637 { id, title, publisher, country, url,
--             excerpt:L2, usedFor:string[] } and the five seeded ids
--             (medlineplus-hgb, cdc-a1c, aha-chol, nhlbi-tg,
--             medlineplus-creatinine) referenced by TestDef.sources and
--             Pattern.source. `code` carries those existing ids unchanged, so
--             /sources and /test/[id] keep resolving.
--
-- DELIBERATE ABSENCE: no pgvector column. The architecture specifies a
-- local/self-hosted FAISS index and nothing in the codebase performs a vector
-- search in PostgreSQL. `external_vector_id` is the join key to that index;
-- adding pgvector later is an additive change, not a migration of this schema.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- rag_sources — publisher-level catalogue
-- ---------------------------------------------------------------------------
create table if not exists public.rag_sources (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,                     -- 'medlineplus-hgb', 'cdc-a1c', ...
  title       text not null,
  publisher   text not null,
  country     text,
  url         text,
  is_clinical_authority boolean not null default true,   -- guideline body vs. general health page
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.rag_sources is
  'Publisher-level source catalogue. `code` preserves the existing Source.id strings from src/lib/data.ts so no client identifier changes.';

drop trigger if exists rag_sources_set_updated_at on public.rag_sources;
create trigger rag_sources_set_updated_at
  before update on public.rag_sources
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- rag_documents — a specific version of a source
-- ---------------------------------------------------------------------------
create table if not exists public.rag_documents (
  id            uuid primary key default gen_random_uuid(),
  rag_source_id uuid not null,
  version       text not null,
  title         text not null,
  url           text,
  language      anvaya_lang_code not null default 'en',
  retrieved_at  timestamptz not null default now(),
  content_sha256 text,
  char_count    int check (char_count is null or char_count >= 0),
  licence_note  text,
  index_version text,                                   -- which FAISS index build contains this document
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),

  constraint docs_fk_source foreign key (rag_source_id) references public.rag_sources (id) on delete cascade,
  constraint docs_version_key unique (rag_source_id, version)
);

comment on table public.rag_documents is
  'Versioned document instances. A guideline that is revised does not invalidate the citations already issued against the older version, because citations point at chunks of a specific document row.';

create index if not exists docs_source_idx on public.rag_documents (rag_source_id) where is_active;
create index if not exists docs_index_version_idx on public.rag_documents (index_version) where is_active;

-- ---------------------------------------------------------------------------
-- rag_chunks — the citable unit
-- ---------------------------------------------------------------------------
create table if not exists public.rag_chunks (
  id                uuid primary key default gen_random_uuid(),
  document_id       uuid not null,
  seq               int not null check (seq >= 0),
  heading           text,
  content           text not null,                      -- public guideline text; contains no patient data by construction
  token_count       int check (token_count is null or token_count >= 0),
  external_vector_id text,                              -- key in the FAISS index
  embedding_model   text,
  embedding_dim     smallint check (embedding_dim is null or embedding_dim > 0),
  is_active         boolean not null default true,
  created_at        timestamptz not null default now(),

  constraint chunks_fk_document foreign key (document_id) references public.rag_documents (id) on delete cascade
);

comment on table public.rag_chunks is
  'The passage a citation points to. `content` is stored here (public clinical guideline text, never PHI) so a citation stays verifiable even if the FAISS index is rebuilt or discarded.';
comment on column public.rag_chunks.external_vector_id is
  'Primary key of the same passage inside the self-hosted FAISS index. PostgreSQL holds the metadata and the text; FAISS holds the vectors.';

create unique index if not exists chunks_doc_seq_key on public.rag_chunks (document_id, seq);
create unique index if not exists chunks_vector_id_key
  on public.rag_chunks (external_vector_id) where external_vector_id is not null;
create index if not exists chunks_active_idx on public.rag_chunks (document_id) where is_active;

-- ---------------------------------------------------------------------------
-- rag_retrievals — one retrieval event
-- ---------------------------------------------------------------------------
create table if not exists public.rag_retrievals (
  id            uuid primary key default gen_random_uuid(),
  query_text    text not null,                          -- the ANONYMISED query; never contains patient identifiers
  query_intent  text,
  language      anvaya_lang_code not null default 'en',
  engine        text not null default 'faiss',
  index_version text,
  top_k         smallint not null check (top_k > 0),
  min_score     numeric(6,5),
  match_count   smallint not null default 0 check (match_count >= 0),
  best_score    numeric(6,5) check (best_score is null or (best_score >= 0 and best_score <= 1)),
  mean_score    numeric(6,5) check (mean_score is null or (mean_score >= 0 and mean_score <= 1)),
  latency_ms    int check (latency_ms is null or latency_ms >= 0),
  created_at    timestamptz not null default now()
);

comment on table public.rag_retrievals is
  'A retrieval event. best_score/mean_score are the retrieval-similarity component of the trust score stored on ai_generations.';

create index if not exists retrievals_created_idx on public.rag_retrievals (created_at desc);
create index if not exists retrievals_lang_idx on public.rag_retrievals (language, created_at desc);

-- ---------------------------------------------------------------------------
-- rag_retrieval_matches — what a retrieval returned
-- ---------------------------------------------------------------------------
create table if not exists public.rag_retrieval_matches (
  id            uuid primary key default gen_random_uuid(),
  retrieval_id  uuid not null,
  rag_chunk_id  uuid not null,
  rank          smallint not null check (rank > 0),
  score         numeric(6,5) not null check (score >= 0 and score <= 1),
  matched_on    text check (matched_on is null or matched_on in ('vector', 'keyword', 'hybrid')),
  created_at    timestamptz not null default now(),

  constraint matches_fk_retrieval foreign key (retrieval_id) references public.rag_retrievals (id) on delete cascade,
  constraint matches_fk_chunk     foreign key (rag_chunk_id)  references public.rag_chunks (id) on delete restrict,
  constraint matches_unique_rank  unique (retrieval_id, rank)
);

comment on table public.rag_retrieval_matches is
  'Per-chunk retrieval outcome. ON DELETE RESTRICT on the chunk: a passage that has been cited must not disappear silently.';

create index if not exists matches_retrieval_idx on public.rag_retrieval_matches (retrieval_id, rank);
create index if not exists matches_chunk_idx on public.rag_retrieval_matches (rag_chunk_id);

-- <<< END db/migrations/0011_rag.sql

-- >>> BEGIN db/migrations/0012_ai.sql
-- ============================================================================
-- Anvaya / RxAnvaya — Supabase migration 0012
-- AI generation + explanations + citations
-- ----------------------------------------------------------------------------
-- Purpose   : Persist the LLM EXPLANATION stage with full provenance (model,
--             prompt version, input version) and a decomposed trust score, and
--             link every explanation to the passages that grounded it.
-- Depends on: 0008, 0010, 0011
-- Fresh safe: YES
--
-- PRIVACY INVARIANT
--   Neither table has a patient_id, report_id or any identifier column. The only
--   outward links are anonymization_id (a pseudonym record) and the subject FKs
--   to test_results / report_patterns, which the RLS layer resolves to an owner.
--   There is therefore no column through which PHI could be written into the AI
--   tables, which is the structural form of "do not design the database in a way
--   that requires sending PII to the LLM".
-- ============================================================================

-- ---------------------------------------------------------------------------
-- ai_generations — one model call
-- ---------------------------------------------------------------------------
create table if not exists public.ai_generations (
  id                uuid primary key default gen_random_uuid(),
  purpose           anvaya_generation_purpose not null,
  status            anvaya_generation_status not null default 'queued',

  -- model / provider provenance (names and versions only, never credentials)
  provider          text,
  model             text,
  model_version     text,
  prompt_key        text,                               -- e.g. 'test_explanation'
  prompt_version    text,                               -- prompts are versioned like code
  system_prompt_sha256 text,
  temperature       numeric(4,3) check (temperature is null or (temperature >= 0 and temperature <= 2)),
  max_tokens        int check (max_tokens is null or max_tokens > 0),

  -- inputs: referenced, not inlined -------------------------------------------
  anonymization_id  uuid,                               -- the PII-free view of the patient/report
  input_version     text,                               -- version of the anonymised payload
  input_snapshot    jsonb,                              -- ANONYMISED inputs only (values, units, statuses)
  retrieval_id      uuid,                               -- the retrieval that grounded this call

  -- outputs ------------------------------------------------------------------
  language          anvaya_lang_code not null default 'en',
  reading_level     anvaya_reading_level,
  raw_output        text,
  output_sha256     text,
  refusal_detected  boolean not null default false,     -- model declined / produced unsafe content
  safety_flags      jsonb not null default '[]'::jsonb,

  -- trust score, stored as components AND as the combined verdict --------------
  model_confidence     numeric(5,4) check (model_confidence is null or (model_confidence >= 0 and model_confidence <= 1)),
  retrieval_similarity numeric(5,4) check (retrieval_similarity is null or (retrieval_similarity >= 0 and retrieval_similarity <= 1)),
  trust_score          numeric(5,4) check (trust_score is null or (trust_score >= 0 and trust_score <= 1)),
  trust_level          anvaya_confidence_level,
  trust_formula        text,                            -- e.g. '0.6*model + 0.4*retrieval' — makes the number auditable
  citation_count    smallint not null default 0 check (citation_count >= 0),

  -- ops ---------------------------------------------------------------------
  tokens_prompt     int check (tokens_prompt is null or tokens_prompt >= 0),
  tokens_completion int check (tokens_completion is null or tokens_completion >= 0),
  latency_ms        int check (latency_ms is null or latency_ms >= 0),
  error_code        text,
  error_message     text,
  started_at        timestamptz,
  finished_at       timestamptz,
  created_at        timestamptz not null default now(),

  constraint gen_fk_anon      foreign key (anonymization_id) references public.anonymization_records (id) on delete set null,
  constraint gen_fk_retrieval foreign key (retrieval_id)     references public.rag_retrievals (id) on delete set null,
  -- a finished generation must have ended
  constraint gen_terminal_needs_finish check (
    status not in ('succeeded', 'failed', 'blocked') or finished_at is not null
  ),
  -- a successful generation produced something
  constraint gen_success_has_output check (status <> 'succeeded' or raw_output is not null),
  -- a failed generation says why
  constraint gen_failure_has_reason check (status <> 'failed' or error_message is not null)
);

comment on table public.ai_generations is
  'One LLM call, with its full provenance. NO PHI: the patient is reachable only via anonymization_id.';
comment on column public.ai_generations.provider is
  'Provider/model NAME only. API keys and secrets must live in Supabase Vault or environment variables — never in a table.';
comment on column public.ai_generations.input_snapshot is
  'The exact anonymised payload sent to the model. Storing it (rather than just a hash) is what lets a reviewer reproduce what the model actually saw.';
comment on column public.ai_generations.trust_formula is
  'The trust score is a blend of model_confidence and retrieval_similarity; recording the formula means a later change in weighting does not silently reinterpret old scores.';

create index if not exists gen_purpose_idx on public.ai_generations (purpose, created_at desc);
create index if not exists gen_status_idx on public.ai_generations (status, created_at desc) where status in ('queued', 'running');
create index if not exists gen_failed_idx on public.ai_generations (created_at desc) where status = 'failed';
create index if not exists gen_anon_idx on public.ai_generations (anonymization_id) where anonymization_id is not null;
create index if not exists gen_retrieval_idx on public.ai_generations (retrieval_id) where retrieval_id is not null;
create index if not exists gen_model_idx on public.ai_generations (provider, model, created_at desc);
create index if not exists gen_lang_idx on public.ai_generations (language, created_at desc);

drop trigger if exists gen_immutable on public.ai_generations;
create trigger gen_immutable
  before update or delete on public.ai_generations
  for each row execute function public.guard_immutable_row();

-- ---------------------------------------------------------------------------
-- ai_explanations — the patient-facing text produced by a generation
-- ---------------------------------------------------------------------------
create table if not exists public.ai_explanations (
  id             uuid primary key default gen_random_uuid(),
  generation_id  uuid not null,
  -- exactly one subject; explicit FKs rather than a (type, id) pair so the
  -- database can actually enforce referential integrity
  subject_test_result_id   uuid,
  subject_report_pattern_id uuid,                       -- FK added in 0013
  subject_report_id        uuid,                        -- report-level summary
  language       anvaya_lang_code not null default 'en',
  reading_level  anvaya_reading_level not null default 'standard',
  version        smallint not null default 1 check (version > 0),
  body_md        text not null,                         -- markdown; the UI already renders Md (src/components/core.tsx)
  body_plain     text,                                  -- flattened text for TTS (speakAll in /test/[id])
  heading        text,
  disclaimer     text,                                  -- the "this is not a diagnosis" line
  is_current     boolean not null default true,
  superseded_by  uuid,
  created_at     timestamptz not null default now(),

  constraint expl_fk_generation foreign key (generation_id) references public.ai_generations (id) on delete restrict,
  constraint expl_fk_test_result foreign key (subject_test_result_id) references public.test_results (id) on delete cascade,
  constraint expl_fk_report foreign key (subject_report_id) references public.lab_reports (id) on delete cascade,
  constraint expl_fk_superseded foreign key (superseded_by) references public.ai_explanations (id) on delete set null,
  constraint expl_exactly_one_subject check (
    anvaya.num_nonnulls(
      subject_test_result_id, subject_report_pattern_id, subject_report_id
    ) = 1
  )
);

comment on table public.ai_explanations is
  'Generated explanation text, versioned per (subject, language, reading level). Editing produces a new version and flips is_current, so the original AI draft is never destroyed.';
comment on column public.ai_explanations.body_plain is
  'Plain-text form used for speech synthesis. The app already builds such a string client-side (speakAll in src/app/test/[id]/page.tsx).';

create unique index if not exists expl_subject_lang_level_version
  on public.ai_explanations (
    coalesce(subject_test_result_id,   '00000000-0000-0000-0000-000000000000'::uuid),
    coalesce(subject_report_pattern_id,'00000000-0000-0000-0000-000000000000'::uuid),
    coalesce(subject_report_id,        '00000000-0000-0000-0000-000000000000'::uuid),
    language, reading_level, version
  );

-- Exactly one current row per subject/language/level.
create unique index if not exists expl_one_current
  on public.ai_explanations (
    coalesce(subject_test_result_id,   '00000000-0000-0000-0000-000000000000'::uuid),
    coalesce(subject_report_pattern_id,'00000000-0000-0000-0000-000000000000'::uuid),
    coalesce(subject_report_id,        '00000000-0000-0000-0000-000000000000'::uuid),
    language, reading_level
  )
  where is_current;

create index if not exists expl_generation_idx on public.ai_explanations (generation_id);
create index if not exists expl_test_result_idx on public.ai_explanations (subject_test_result_id) where subject_test_result_id is not null;
create index if not exists expl_report_idx on public.ai_explanations (subject_report_id) where subject_report_id is not null;

drop trigger if exists expl_immutable on public.ai_explanations;
create trigger expl_immutable
  before delete on public.ai_explanations
  for each row execute function public.guard_immutable_row();

-- is_current flips are legitimate updates, but the text of an existing
-- explanation must not be rewritten in place.
create or replace function public.guard_explanation_body()
returns trigger
language plpgsql
as $$
begin
  if new.body_md      is distinct from old.body_md
  or new.language     is distinct from old.language
  or new.reading_level is distinct from old.reading_level
  or new.generation_id is distinct from old.generation_id
  or new.version      is distinct from old.version then
    raise exception 'anvaya: ai_explanations content is immutable; insert a new version instead (explanation %)', old.id;
  end if;
  return new;
end;
$$;

drop trigger if exists expl_body_guard on public.ai_explanations;
create trigger expl_body_guard
  before update on public.ai_explanations
  for each row execute function public.guard_explanation_body();

-- ---------------------------------------------------------------------------
-- explanation_citations — "what source supported this statement?"
-- ---------------------------------------------------------------------------
create table if not exists public.explanation_citations (
  id                uuid primary key default gen_random_uuid(),
  explanation_id    uuid not null,
  rag_chunk_id      uuid not null,
  retrieval_match_id uuid,
  citation_index    smallint not null check (citation_index > 0),
  rank              smallint check (rank is null or rank > 0),
  similarity        numeric(6,5) check (similarity is null or (similarity >= 0 and similarity <= 1)),
  quoted_text       text,                               -- the exact span relied upon
  created_at        timestamptz not null default now(),

  constraint cit_fk_explanation foreign key (explanation_id) references public.ai_explanations (id) on delete cascade,
  constraint cit_fk_chunk       foreign key (rag_chunk_id)   references public.rag_chunks (id) on delete restrict,
  constraint cit_fk_match       foreign key (retrieval_match_id) references public.rag_retrieval_matches (id) on delete set null,
  constraint cit_unique_chunk   unique (explanation_id, rag_chunk_id)
);

comment on table public.explanation_citations is
  'Explanation -> chunk -> document -> source. This chain is what answers "what source supported this statement?" and it survives FAISS index rebuilds because the chunk text is persisted.';
comment on column public.explanation_citations.rag_chunk_id is
  'ON DELETE RESTRICT: a passage behind a published explanation cannot be deleted without first dealing with the explanation that cites it.';

create index if not exists cit_explanation_idx on public.explanation_citations (explanation_id, citation_index);
create index if not exists cit_chunk_idx on public.explanation_citations (rag_chunk_id);

drop trigger if exists cit_immutable on public.explanation_citations;
create trigger cit_immutable
  before update or delete on public.explanation_citations
  for each row execute function public.guard_immutable_row();

-- <<< END db/migrations/0012_ai.sql

-- >>> BEGIN db/migrations/0013_patterns.sql
-- ============================================================================
-- Anvaya / RxAnvaya — Supabase migration 0013
-- Multi-test patterns (the clinical knowledge graph findings)
-- ----------------------------------------------------------------------------
-- Purpose   : Model the "Multi-test reasoning" pipeline stage: related results
--             grouped into a finding with a direction per member.
-- Depends on: 0006, 0007, 0012
-- Fresh safe: YES
-- Contract  : Maps onto the Pattern interface in src/lib/data.ts:901-910
--               { id, title:L2, nodes:[{test, arrow:"up"|"down"|"flat", note?}],
--                 expl:L2, risk:L2, disclaimer:L2, source:string, conf }
--             and the three seeded ids pattern-lipid / pattern-blood /
--             pattern-sugar rendered by src/app/insights/page.tsx and
--             src/app/dashboard/page.tsx.
--
--             pattern_templates holds the STATIC catalogue (the three known
--             pattern shapes, whose titles/risks are fixed clinical content).
--             report_patterns is the per-report INSTANCE. The narrative text
--             (expl/risk/disclaimer) is NOT duplicated here — it lives in
--             ai_explanations with subject_report_pattern_id set, so patterns
--             get the same language x reading-level versioning as every other
--             explanation.
--
--             KG_CLUSTERS (src/lib/data.ts:1026) is a static visual layout for
--             the knowledge-graph graphic, not patient data, so it is
--             deliberately NOT given a table.
-- ============================================================================

create table if not exists public.pattern_templates (
  id             uuid primary key default gen_random_uuid(),
  code           text not null unique,                  -- 'pattern-lipid' | 'pattern-blood' | 'pattern-sugar'
  title_en       text not null,
  title_hi       text,
  default_risk_en text,
  default_risk_hi text,
  default_disclaimer_en text,
  default_disclaimer_hi text,
  description    text,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

comment on table public.pattern_templates is
  'Static catalogue of multi-test pattern shapes. `code` preserves the existing Pattern.id strings from src/lib/data.ts.';

drop trigger if exists pt_set_updated_at on public.pattern_templates;
create trigger pt_set_updated_at
  before update on public.pattern_templates
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- report_patterns — a pattern instance detected in one report
-- ---------------------------------------------------------------------------
create table if not exists public.report_patterns (
  id             uuid primary key default gen_random_uuid(),
  report_id      uuid not null,
  template_id    uuid not null,
  detection      text not null default 'rule'
                 check (detection in ('rule', 'model', 'clinician')),
  generation_id  uuid,                                  -- the AI call that narrated it, if any
  rag_source_id  uuid,                                  -- Pattern.source
  confidence_level anvaya_confidence_level,             -- Pattern.conf.level
  confidence_pct smallint check (confidence_pct is null or (confidence_pct >= 0 and confidence_pct <= 100)),
  is_significant boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint rp_fk_report   foreign key (report_id)   references public.lab_reports (id) on delete cascade,
  constraint rp_fk_template foreign key (template_id) references public.pattern_templates (id) on delete restrict,
  constraint rp_fk_generation foreign key (generation_id) references public.ai_generations (id) on delete set null,
  constraint rp_fk_source   foreign key (rag_source_id) references public.rag_sources (id) on delete set null
);

comment on table public.report_patterns is
  'A multi-test finding for a specific report. `detection` records whether a rule or a model spotted the pattern — the pattern itself never changes a deterministic test status.';

create unique index if not exists rp_one_per_template_per_report
  on public.report_patterns (report_id, template_id);
create index if not exists rp_report_idx on public.report_patterns (report_id) where is_significant;

drop trigger if exists rp_set_updated_at on public.report_patterns;
create trigger rp_set_updated_at
  before update on public.report_patterns
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- report_pattern_members — Pattern.nodes
-- ---------------------------------------------------------------------------
create table if not exists public.report_pattern_members (
  id              uuid primary key default gen_random_uuid(),
  report_pattern_id uuid not null,
  lab_test_id     uuid not null,
  test_result_id  uuid,
  direction       anvaya_trend_dir not null default 'flat',   -- Pattern.nodes[].arrow
  note_en         text,
  note_hi         text,
  position        smallint not null default 0,
  created_at      timestamptz not null default now(),

  constraint rpm_fk_pattern foreign key (report_pattern_id) references public.report_patterns (id) on delete cascade,
  constraint rpm_fk_test    foreign key (lab_test_id)  references public.lab_test_catalog (id) on delete restrict,
  constraint rpm_fk_result  foreign key (test_result_id) references public.test_results (id) on delete set null,
  constraint rpm_unique_test unique (report_pattern_id, lab_test_id)
);

comment on table public.report_pattern_members is
  'Pattern.nodes: which tests participate and which way each is moving. `direction` is a trend descriptor, not a re-classification of the deterministic status.';

create index if not exists rpm_pattern_idx on public.report_pattern_members (report_pattern_id, position);
create index if not exists rpm_test_idx on public.report_pattern_members (lab_test_id);

-- ---------------------------------------------------------------------------
-- Close the ai_explanations -> report_patterns loop
-- ---------------------------------------------------------------------------
do $do$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'expl_fk_report_pattern'
      and conrelid = 'public.ai_explanations'::regclass
  ) then
    alter table public.ai_explanations
      add constraint expl_fk_report_pattern
      foreign key (subject_report_pattern_id)
      references public.report_patterns (id)
      on delete cascade;
  end if;
end
$do$;

create index if not exists expl_pattern_idx
  on public.ai_explanations (subject_report_pattern_id)
  where subject_report_pattern_id is not null;

-- <<< END db/migrations/0013_patterns.sql

-- >>> BEGIN db/migrations/0014_review_release.sql
-- ============================================================================
-- Anvaya / RxAnvaya — Supabase migration 0014
-- Doctor review workflow, report versions, translations, releases
-- ----------------------------------------------------------------------------
-- Purpose   : The DOCTOR REVIEW -> FINAL REPORT -> PATIENT stages as a real
--             state machine with reviewer identity, version history and an
--             explicit release, instead of an `approved boolean`.
-- Depends on: 0003, 0004, 0007, 0012
-- Fresh safe: YES
-- Contract  : NEW. The shipped app has no reviewer at all: src/app/doctor/page.tsx
--             is a patient-facing printable summary ("A clinician-style view to
--             share with your doctor") whose Download/Share buttons only call
--             window.print() and a toast. That page keeps working unchanged;
--             this migration adds the server-side workflow behind a real review.
--
--             draft -> pending_review -> needs_edit -> approved -> released
--             Only an `approved` version can be released, and only a released
--             version is patient-facing (see the RLS policies in 0018 and
--             anvaya.release_report in 0017).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- report_versions — immutable content snapshots
-- ---------------------------------------------------------------------------
create table if not exists public.report_versions (
  id                uuid primary key default gen_random_uuid(),
  report_id         uuid not null,
  version_no        smallint not null check (version_no > 0),
  origin            anvaya_version_origin not null,
  based_on_version_id uuid,
  edited_by         uuid,                               -- profiles.id of the doctor who made this edit
  change_summary    text,
  -- Frozen document structure for this version: which explanations are
  -- included, section order, doctor's clinical notes. This is an immutable
  -- document artefact rather than queryable application state, which is why it
  -- is jsonb; every fact the app QUERIES (results, statuses, reviews, releases)
  -- lives in its own table.
  content_snapshot  jsonb not null default '{}'::jsonb,
  doctor_notes      text,
  is_locked         boolean not null default false,
  created_by        uuid,
  created_at        timestamptz not null default now(),

  constraint rv_fk_report foreign key (report_id) references public.lab_reports (id) on delete restrict,
  constraint rv_fk_based_on foreign key (based_on_version_id) references public.report_versions (id) on delete set null,
  constraint rv_fk_edited_by foreign key (edited_by) references public.profiles (id) on delete set null,
  constraint rv_fk_created_by foreign key (created_by) references public.profiles (id) on delete set null,
  constraint rv_version_key unique (report_id, version_no),
  constraint rv_doctor_edits_have_author check (
    origin <> 'doctor_edit' or edited_by is not null
  )
);

comment on table public.report_versions is
  'Version history of a report''s narrative content. The AI draft is version 1 with origin ai_draft; a doctor edit creates version 2 rather than overwriting version 1, so the original draft is always recoverable.';
comment on column public.report_versions.content_snapshot is
  'Immutable document artefact (section order, included explanation ids, doctor notes). Deliberately the ONLY jsonb blob in the review path — queryable state is relational.';

create index if not exists rv_report_idx on public.report_versions (report_id, version_no desc);
create index if not exists rv_editor_idx on public.report_versions (edited_by) where edited_by is not null;

-- Versions are immutable once created.
drop trigger if exists rv_immutable on public.report_versions;
create trigger rv_immutable
  before update or delete on public.report_versions
  for each row execute function public.guard_immutable_row();

-- ---------------------------------------------------------------------------
-- report_translations — the same validated facts, other languages
-- ---------------------------------------------------------------------------
create table if not exists public.report_translations (
  id               uuid primary key default gen_random_uuid(),
  report_version_id uuid not null,
  language         anvaya_lang_code not null,
  narrative_md     text not null,
  narrative_plain  text,                                -- TTS-ready
  authored_by      anvaya_text_author not null default 'ai',
  generation_id    uuid,
  reviewed_by      uuid,
  is_current       boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),

  constraint rt_fk_version foreign key (report_version_id) references public.report_versions (id) on delete cascade,
  constraint rt_fk_generation foreign key (generation_id) references public.ai_generations (id) on delete set null,
  constraint rt_fk_reviewed_by foreign key (reviewed_by) references public.profiles (id) on delete set null,
  constraint rt_unique_lang unique (report_version_id, language)
);

comment on table public.report_translations is
  'Language variants of one report version. The underlying validated facts are NOT duplicated per language — only the narrative is — so a translation can never disagree with the deterministic classification.';
comment on column public.report_translations.authored_by is
  'Distinguishes machine translation from a human/clinician-reviewed translation, which matters before a translation is released to a patient.';

create index if not exists rt_version_idx on public.report_translations (report_version_id, language) where is_current;
create index if not exists rt_lang_idx on public.report_translations (language);

drop trigger if exists rt_set_updated_at on public.report_translations;
create trigger rt_set_updated_at
  before update on public.report_translations
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- doctor_reviews — the workflow record
-- ---------------------------------------------------------------------------
create table if not exists public.doctor_reviews (
  id                uuid primary key default gen_random_uuid(),
  report_id         uuid not null,
  report_version_id uuid not null,
  doctor_id         uuid not null,
  status            anvaya_review_status not null default 'draft',
  assigned_at       timestamptz not null default now(),
  assigned_by       uuid,
  opened_at         timestamptz,
  decision_at       timestamptz,
  signed_at         timestamptz,
  signature_ref     text,                               -- storage key of a signature image, if captured
  comments          text,
  rejection_reason  text,
  edits_summary     text,
  previous_status   anvaya_review_status,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint dr_fk_report  foreign key (report_id) references public.lab_reports (id) on delete restrict,
  constraint dr_fk_version foreign key (report_version_id) references public.report_versions (id) on delete restrict,
  constraint dr_fk_doctor  foreign key (doctor_id) references public.doctors (id) on delete restrict,
  constraint dr_fk_assigned_by foreign key (assigned_by) references public.profiles (id) on delete set null,

  -- workflow integrity ------------------------------------------------------
  constraint dr_decision_requires_decision_at check (
    status not in ('approved', 'needs_edit', 'withdrawn') or decision_at is not null
  ),
  constraint dr_signed_requires_approval check (
    signed_at is null or status in ('approved', 'released')
  ),
  constraint dr_rejection_requires_reason check (
    status <> 'needs_edit' or rejection_reason is not null
  )
);

comment on table public.doctor_reviews is
  'One review record per (report, version, doctor). Reviewer identity is a hard FK to doctors, so no review can exist without an attributable clinician.';
comment on column public.doctor_reviews.status is
  'draft -> pending_review -> needs_edit -> approved -> released. Transitions are validated in anvaya.set_review_status (0017); this column is never written directly by the client.';

-- A doctor holds at most one open review per report version.
create unique index if not exists dr_one_open_per_version
  on public.doctor_reviews (report_version_id, doctor_id)
  where status in ('draft', 'pending_review', 'needs_edit');

-- Doctor review queue: "what is waiting for me, oldest first".
create index if not exists dr_queue_idx
  on public.doctor_reviews (doctor_id, assigned_at)
  where status = 'pending_review';

create index if not exists dr_report_idx on public.doctor_reviews (report_id, created_at desc);
create index if not exists dr_status_idx on public.doctor_reviews (status, assigned_at);
create index if not exists dr_signed_idx on public.doctor_reviews (signed_at desc) where signed_at is not null;

drop trigger if exists dr_set_updated_at on public.doctor_reviews;
create trigger dr_set_updated_at
  before update on public.doctor_reviews
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- report_releases — the patient-facing final report
-- ---------------------------------------------------------------------------
create table if not exists public.report_releases (
  id                uuid primary key default gen_random_uuid(),
  report_id         uuid not null,
  report_version_id uuid not null,
  review_id         uuid,
  released_by       uuid not null,                      -- the clinician who signed
  released_at       timestamptz not null default now(),
  release_channel   text check (release_channel is null or release_channel in ('app', 'email', 'sms', 'clinic', 'api')),
  is_active         boolean not null default true,
  superseded_at     timestamptz,
  superseded_by     uuid,
  revoked_at        timestamptz,
  revoked_reason    text,
  pdf_path          text,                               -- storage key of the exported PDF
  tts_path          text,                               -- storage key of narrated audio, if produced
  created_at        timestamptz not null default now(),

  constraint rel_fk_report  foreign key (report_id) references public.lab_reports (id) on delete restrict,
  constraint rel_fk_version foreign key (report_version_id) references public.report_versions (id) on delete restrict,
  constraint rel_fk_review  foreign key (review_id) references public.doctor_reviews (id) on delete set null,
  constraint rel_fk_released_by foreign key (released_by) references public.profiles (id) on delete restrict,
  constraint rel_fk_superseded_by foreign key (superseded_by) references public.report_releases (id) on delete set null,
  constraint rel_revoked_needs_ts check (revoked_at is null or is_active = false)
);

comment on table public.report_releases is
  'The FINAL REPORT stage. A row here is the only thing that makes a report patient-facing. Only a version whose review is `approved` may be released — enforced by anvaya.release_report (0017).';

-- Exactly one active release per report.
create unique index if not exists rel_one_active_per_report
  on public.report_releases (report_id)
  where is_active;

create index if not exists rel_report_idx on public.report_releases (report_id, released_at desc);
create index if not exists rel_active_idx on public.report_releases (released_at desc) where is_active;
create index if not exists rel_review_idx on public.report_releases (review_id) where review_id is not null;

-- <<< END db/migrations/0014_review_release.sql

-- >>> BEGIN db/migrations/0015_qa_voice.sql
-- ============================================================================
-- Anvaya / RxAnvaya — Supabase migration 0015
-- Voice sessions, Q&A messages, answer feedback
-- ----------------------------------------------------------------------------
-- Purpose   : Persist only what the voice/Q&A feature actually needs: a session,
--             the question, its transcript, the grounded answer, a reference to
--             any audio, the language, and the sources/confidence the UI shows.
-- Depends on: 0003, 0007, 0012
-- Fresh safe: YES
-- Contract  : Maps onto the two API routes that already exist:
--               POST /api/answer   request  { q: string, lang: string }
--                                  response { matched, answer, sources: number,
--                                               confidence: "high" | "moderate" }
--                                  (src/app/api/answer/route.ts)
--               POST /api/feedback request  { helpful: boolean }
--                                  response { ok, persisted: false, mode: "demo" }
--                                  (src/app/api/feedback/route.ts)
--             `sources_count` and `confidence_level` are the persistence of the
--             two response fields; `answer_feedback` is what turns the current
--             `persisted: false` stub into a real record.
--
--             Audio is NOT stored in PostgreSQL. src/components/voice.tsx
--             simulates STT and uses the browser's SpeechSynthesis for playback,
--             so there is no audio payload today; when real STT/TTS is wired up
--             the bytes go to Supabase Storage and these columns hold the key.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- voice_sessions
-- ---------------------------------------------------------------------------
create table if not exists public.voice_sessions (
  id           uuid primary key default gen_random_uuid(),
  patient_id   uuid not null,
  lab_report_id uuid,                                   -- the report the conversation is about
  channel      anvaya_qa_channel not null default 'voice',
  language     anvaya_lang_code not null default 'en',
  stt_engine   text,
  tts_engine   text,
  device_hint  text,                                    -- coarse device/locale info, never an identifier
  started_at   timestamptz not null default now(),
  ended_at     timestamptz,
  turn_count   smallint not null default 0 check (turn_count >= 0),
  created_at   timestamptz not null default now(),

  constraint vs_fk_patient foreign key (patient_id) references public.patients (id) on delete cascade,
  constraint vs_fk_report  foreign key (lab_report_id) references public.lab_reports (id) on delete set null,
  constraint vs_ended_after_start check (ended_at is null or ended_at >= started_at)
);

comment on table public.voice_sessions is
  'A conversation container. Scoped to the patient and, optionally, to the report being discussed, so answers can be constrained to that report''s results.';

create index if not exists vs_patient_idx on public.voice_sessions (patient_id, started_at desc);
create index if not exists vs_report_idx on public.voice_sessions (lab_report_id) where lab_report_id is not null;
create index if not exists vs_open_idx on public.voice_sessions (started_at desc) where ended_at is null;

-- ---------------------------------------------------------------------------
-- qa_messages
-- ---------------------------------------------------------------------------
create table if not exists public.qa_messages (
  id                uuid primary key default gen_random_uuid(),
  session_id        uuid not null,
  parent_message_id uuid,
  role              anvaya_message_role not null,
  body_md           text not null,
  body_plain        text,                               -- TTS-ready form
  language          anvaya_lang_code not null default 'en',
  -- voice specifics
  transcript        text,                               -- STT output for a user turn
  transcript_confidence numeric(5,4) check (transcript_confidence is null or (transcript_confidence >= 0 and transcript_confidence <= 1)),
  audio_bucket      text,
  audio_path        text,                               -- storage key; the audio itself is never in PostgreSQL
  audio_duration_ms int check (audio_duration_ms is null or audio_duration_ms >= 0),
  -- grounding, mirroring the /api/answer response shape
  generation_id     uuid,
  matched_topic     text,                               -- response field `matched`
  sources_count     smallint not null default 0 check (sources_count >= 0),
  confidence_level  anvaya_confidence_level,            -- response field `confidence`
  is_fallback       boolean not null default false,     -- the FALLBACK answer in /api/answer
  latency_ms        int check (latency_ms is null or latency_ms >= 0),
  created_at        timestamptz not null default now(),

  constraint qa_fk_session foreign key (session_id) references public.voice_sessions (id) on delete cascade,
  constraint qa_fk_parent  foreign key (parent_message_id) references public.qa_messages (id) on delete set null,
  constraint qa_fk_generation foreign key (generation_id) references public.ai_generations (id) on delete set null,
  constraint qa_audio_pair check (
    (audio_bucket is null and audio_path is null) or
    (audio_bucket is not null and audio_path is not null)
  ),
  constraint qa_assistant_needs_generation check (
    role <> 'assistant' or generation_id is not null or is_fallback
  )
);

comment on table public.qa_messages is
  'One row per chat turn. The app already models messages as { role: "user" | "assistant", text, sources?, confidence? } (src/app/ask/page.tsx), so this shape is a direct persistence of that structure.';
comment on column public.qa_messages.audio_path is
  'Reference into a PRIVATE storage bucket. Raw audio is health data and must not be served from a public bucket.';

create index if not exists qa_session_idx on public.qa_messages (session_id, created_at);
create index if not exists qa_parent_idx on public.qa_messages (parent_message_id) where parent_message_id is not null;
create index if not exists qa_generation_idx on public.qa_messages (generation_id) where generation_id is not null;
create index if not exists qa_created_idx on public.qa_messages (created_at desc);

drop trigger if exists qa_immutable on public.qa_messages;
create trigger qa_immutable
  before update or delete on public.qa_messages
  for each row execute function public.guard_immutable_row();

-- ---------------------------------------------------------------------------
-- answer_feedback
-- ---------------------------------------------------------------------------
create table if not exists public.answer_feedback (
  id            uuid primary key default gen_random_uuid(),
  qa_message_id uuid not null,
  patient_id    uuid not null,
  helpful       boolean not null,
  comment       text,
  created_at    timestamptz not null default now(),

  constraint fb_fk_message foreign key (qa_message_id) references public.qa_messages (id) on delete cascade,
  constraint fb_fk_patient foreign key (patient_id) references public.patients (id) on delete cascade,
  constraint fb_one_per_patient unique (qa_message_id, patient_id)
);

comment on table public.answer_feedback is
  'Helpfulness votes from the Ask AI screen. Replaces the current no-op endpoint that returns { persisted: false, mode: "demo" }.';

create index if not exists fb_message_idx on public.answer_feedback (qa_message_id);
create index if not exists fb_patient_idx on public.answer_feedback (patient_id, created_at desc);

-- Votes are append-only; a changed mind is a new row in a real design, but the
-- unique constraint above means one vote per patient per answer, so we allow the
-- client to revoke by deleting its own row (policy in 0018) rather than editing.

-- <<< END db/migrations/0015_qa_voice.sql

-- >>> BEGIN db/migrations/0016_audit_deletion_errors.sql
-- ============================================================================
-- Anvaya / RxAnvaya — Supabase migration 0016
-- Audit trail, deletion requests, persisted errors
-- ----------------------------------------------------------------------------
-- Purpose   : Append-only, hash-chained audit records; an explicit erasure
--             workflow; and durable failure records for pipeline components.
-- Depends on: 0001, 0002, 0003
-- Fresh safe: YES
-- Contract  : NEW. Nothing in the current codebase writes an audit record —
--             src/app/how/page.tsx:117-120 merely asserts "Reports can be
--             deleted after processing; data encrypted in transit and at rest."
--             These tables are what make that assertion checkable.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- audit_logs — append-only, hash-chained
-- ---------------------------------------------------------------------------
create table if not exists public.audit_logs (
  id            bigint generated always as identity primary key,
  occurred_at   timestamptz not null default now(),
  actor_id      uuid,                                   -- profiles.id; NULL for system jobs
  actor_role    anvaya_role,
  action        text not null,                          -- see the check constraint below
  entity_type   text not null,                          -- 'lab_report' | 'test_result' | 'doctor_review' | ...
  entity_id     text,                                   -- text so any PK type fits
  patient_id    uuid,                                   -- NULL-able so erasure can de-link without destroying the record
  report_id     uuid,
  outcome       text not null default 'success'
                check (outcome in ('success', 'failure', 'denied')),
  metadata      jsonb not null default '{}'::jsonb,
  ip_address    inet,
  user_agent    text,
  prev_hash     text,                                   -- row_hash of the preceding record
  row_hash      text not null,                          -- sha256 over this row + prev_hash

  -- audit rows must never carry the payload of a clinical value or a report body
  constraint audit_action_known check (action in (
    -- consent
    'consent.granted', 'consent.withdrawn', 'consent.expired', 'consent.policy_published',
    -- report lifecycle
    'report.uploaded', 'report.created', 'report.deleted', 'report.restored',
    'report.processing_started', 'report.processing_failed', 'report.processing_completed',
    -- results & determinism
    'result.extracted', 'result.corrected', 'result.validated', 'result.revalidated',
    -- privacy
    'anonymization.performed', 'pii.accessed',
    -- AI
    'ai.generation_requested', 'ai.generation_failed', 'ai.explanation_created',
    -- review & release
    'review.assigned', 'review.opened', 'review.edit_made', 'review.approved',
    'review.rejected', 'review.signed', 'report.released', 'release.revoked',
    -- access control & erasure
    'access.granted', 'access.revoked', 'access.denied', 'auth.login', 'auth.logout',
    'deletion.requested', 'deletion.completed', 'deletion.rejected', 'deletion.failed',
    -- admin
    'admin.config_changed', 'admin.reference_range_updated'
  ))
);

comment on table public.audit_logs is
  'Append-only security audit trail. Hash-chained: each row commits to the previous row''s hash, so silent deletion or editing of history is detectable. No UPDATE or DELETE path exists.';
comment on column public.audit_logs.patient_id is
  'Nullable on purpose. On erasure the link can be cleared while the FACT of the action is retained, which is how "minimal compliance information" survives without retaining PHI.';
comment on column public.audit_logs.metadata is
  'Non-sensitive context only. Never store a clinical value, a report body, or a credential here.';

create index if not exists audit_occurred_idx on public.audit_logs (occurred_at desc);
create index if not exists audit_patient_idx on public.audit_logs (patient_id, occurred_at desc) where patient_id is not null;
create index if not exists audit_report_idx on public.audit_logs (report_id, occurred_at desc) where report_id is not null;
create index if not exists audit_actor_idx on public.audit_logs (actor_id, occurred_at desc) where actor_id is not null;
create index if not exists audit_action_idx on public.audit_logs (action, occurred_at desc);
create index if not exists audit_entity_idx on public.audit_logs (entity_type, entity_id);
create index if not exists audit_denied_idx on public.audit_logs (occurred_at desc) where outcome = 'denied';

-- Hash chain + immutability --------------------------------------------------
create or replace function public.audit_seal_row()
returns trigger
language plpgsql
as $$
declare
  v_prev text;
begin
  select row_hash into v_prev from public.audit_logs order by id desc limit 1;
  new.prev_hash := v_prev;
  -- sha256() takes bytea, not text: the explicit cast is required.
  new.row_hash := encode(sha256((
    coalesce(v_prev, 'genesis') || '|' ||
    new.occurred_at::text || '|' ||
    coalesce(new.actor_id::text, '-') || '|' ||
    coalesce(new.actor_role::text, '-') || '|' ||
    new.action || '|' ||
    new.entity_type || '|' ||
    coalesce(new.entity_id, '-') || '|' ||
    coalesce(new.patient_id::text, '-') || '|' ||
    coalesce(new.report_id::text, '-') || '|' ||
    new.outcome || '|' ||
    new.metadata::text
  )::bytea), 'hex');
  return new;
end;
$$;

comment on function public.audit_seal_row() is
  'Computes prev_hash and row_hash on insert. Because audit_logs has no UPDATE/DELETE trigger allowance and no client policy, the chain can only grow.';

drop trigger if exists audit_seal on public.audit_logs;
create trigger audit_seal
  before insert on public.audit_logs
  for each row execute function public.audit_seal_row();

-- The one legitimate mutation of an audit row is DE-LINKING it from a patient
-- during erasure (see anvaya.hard_delete_patient in 0017). Everything else —
-- editing content, or any delete — is refused.
create or replace function public.guard_audit_row()
returns trigger
language plpgsql
as $$
declare
  v_erasure text;
  v_same    boolean;
begin
  if tg_op = 'DELETE' then
    raise exception 'anvaya: audit_logs is append-only; DELETE is never permitted';
  end if;

  v_erasure := current_setting('anvaya.erasure_in_progress', true);

  v_same :=
        new.occurred_at = old.occurred_at
    and new.actor_id    is not distinct from old.actor_id
    and new.actor_role  is not distinct from old.actor_role
    and new.action      = old.action
    and new.entity_type = old.entity_type
    and new.entity_id   is not distinct from old.entity_id
    and new.report_id   is not distinct from old.report_id
    and new.outcome     = old.outcome
    and new.metadata    = old.metadata
    and new.prev_hash   is not distinct from old.prev_hash
    and new.row_hash    = old.row_hash;

  if v_erasure = 'on' and v_same and old.patient_id is not null and new.patient_id is null then
    return new;   -- sanctioned de-link during erasure
  end if;

  raise exception 'anvaya: audit_logs row % is immutable', old.id;
end;
$$;

comment on function public.guard_audit_row() is
  'DELETE always refused. UPDATE refused unless the session is inside a sanctioned erasure (anvaya.erasure_in_progress = on) and the ONLY change is clearing patient_id, which de-links the record from the person while preserving the fact that the action happened.';

drop trigger if exists audit_immutable on public.audit_logs;
create trigger audit_immutable
  before update or delete on public.audit_logs
  for each row execute function public.guard_audit_row();

-- ---------------------------------------------------------------------------
-- deletion_requests — the erasure workflow
-- ---------------------------------------------------------------------------
create table if not exists public.deletion_requests (
  id            uuid primary key default gen_random_uuid(),
  patient_id    uuid not null,
  requested_by  uuid,                                   -- profiles.id (self-service or staff on behalf)
  scope         anvaya_deletion_scope not null,
  lab_report_id uuid,                                   -- set when scope = single_report
  reason        text,
  status        anvaya_deletion_status not null default 'requested',
  requested_at  timestamptz not null default now(),
  started_at    timestamptz,
  completed_at  timestamptz,
  verified_by   uuid,
  -- What was destroyed vs. what was legitimately kept.
  items_deleted jsonb not null default '{}'::jsonb,
  retained_audit boolean not null default true,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint delreq_fk_patient foreign key (patient_id) references public.patients (id) on delete cascade,
  constraint delreq_fk_report  foreign key (lab_report_id) references public.lab_reports (id) on delete set null,
  constraint delreq_fk_requested_by foreign key (requested_by) references public.profiles (id) on delete set null,
  constraint delreq_fk_verified_by foreign key (verified_by) references public.profiles (id) on delete set null,
  constraint delreq_single_needs_report check (scope <> 'single_report' or lab_report_id is not null),
  constraint delreq_completed_needs_ts check (status <> 'completed' or completed_at is not null)
);

comment on table public.deletion_requests is
  'Erasure is a workflow, not a DELETE statement. The request row survives completion and records what was destroyed, so "the patient asked and we did it" remains provable after the PHI is gone.';
comment on column public.deletion_requests.retained_audit is
  'TRUE by default: the audit_logs entries survive erasure (with patient_id cleared), because a record that a deletion happened is compliance information, not PHI.';

create index if not exists delreq_patient_idx on public.deletion_requests (patient_id, requested_at desc);
create index if not exists delreq_open_idx on public.deletion_requests (requested_at)
  where status in ('requested', 'in_progress');
create index if not exists delreq_report_idx on public.deletion_requests (lab_report_id) where lab_report_id is not null;

drop trigger if exists delreq_set_updated_at on public.deletion_requests;
create trigger delreq_set_updated_at
  before update on public.deletion_requests
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- system_errors — persisted failures
-- ---------------------------------------------------------------------------
create table if not exists public.system_errors (
  id            uuid primary key default gen_random_uuid(),
  occurred_at   timestamptz not null default now(),
  component     anvaya_component not null,
  severity      anvaya_severity not null default 'error',
  error_code    text not null,
  message       text not null,
  stack_trace   text,
  context       jsonb not null default '{}'::jsonb,     -- ANONYMISED context only
  lab_report_id uuid,
  job_id        uuid,
  generation_id uuid,
  fingerprint   text,                                   -- groups repeats of the same failure
  occurrence_count int not null default 1 check (occurrence_count > 0),
  first_seen_at timestamptz not null default now(),
  last_seen_at  timestamptz not null default now(),
  resolved_at   timestamptz,
  resolved_by   uuid,
  resolution    text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint err_fk_report foreign key (lab_report_id) references public.lab_reports (id) on delete set null,
  constraint err_fk_job    foreign key (job_id) references public.report_processing_jobs (id) on delete set null,
  constraint err_fk_generation foreign key (generation_id) references public.ai_generations (id) on delete set null,
  constraint err_fk_resolved_by foreign key (resolved_by) references public.profiles (id) on delete set null,
  constraint err_resolved_needs_ts check (resolved_at is null or resolution is not null),
  constraint err_window check (last_seen_at >= first_seen_at)
);

comment on table public.system_errors is
  'Durable failure records for OCR, parsing, validation, RAG and LLM stages. `context` must be anonymised — an error payload is a classic accidental PHI leak.';
comment on column public.system_errors.generation_id is
  'ON DELETE SET NULL: ai_generations is immutable, so this link is only ever dropped by an explicit administrative purge.';

create index if not exists err_recent_idx on public.system_errors (occurred_at desc);
create index if not exists err_open_idx on public.system_errors (severity, occurred_at desc) where resolved_at is null;
create index if not exists err_fingerprint_idx on public.system_errors (fingerprint, last_seen_at desc) where fingerprint is not null;
create index if not exists err_component_idx on public.system_errors (component, occurred_at desc);
create index if not exists err_report_idx on public.system_errors (lab_report_id) where lab_report_id is not null;

drop trigger if exists err_set_updated_at on public.system_errors;
create trigger err_set_updated_at
  before update on public.system_errors
  for each row execute function public.set_updated_at();

-- <<< END db/migrations/0016_audit_deletion_errors.sql

-- >>> BEGIN db/migrations/0017_functions.sql
-- ============================================================================
-- Anvaya / RxAnvaya — Supabase migration 0017
-- Privileged functions: identity helpers, audit writer, corrections,
-- review transitions, release, erasure
-- ----------------------------------------------------------------------------
-- Purpose   : Put every state transition that must not be client-controlled
--             behind a SECURITY DEFINER function in the non-exposed `anvaya`
--             schema. The browser gets no direct write policy on any of these
--             tables; it calls a function, and the function enforces the rule
--             and writes the audit row in the same transaction.
-- Depends on: 0003-0016 (all tables)
-- Fresh safe: YES
--
-- SECURITY MODEL
--   * SECURITY DEFINER functions run as the table owner, so they can write
--     despite RLS. That is exactly why they must contain the authorisation
--     check themselves — every function below does.
--   * `set search_path` is pinned on every one of them. Without it a
--     SECURITY DEFINER function is vulnerable to search_path hijacking.
--   * None of these are added to pgrst.db_schemas, so PostgREST will not expose
--     them as RPC endpoints. The Next.js server (service role or a thin API
--     route) invokes them; the browser cannot.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Identity helpers
-- ---------------------------------------------------------------------------
create or replace function anvaya.current_role()
returns anvaya_role
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select role from public.profiles where id = auth.uid();
$$;

comment on function anvaya.current_role() is
  'Role of the signed-in user. SECURITY DEFINER so an RLS policy can read profiles without needing a recursive policy on profiles itself.';

create or replace function anvaya.current_patient_id()
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select id from public.patients where profile_id = auth.uid();
$$;

create or replace function anvaya.current_doctor_id()
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select id from public.doctors where profile_id = auth.uid();
$$;

create or replace function anvaya.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce((select role = 'admin' from public.profiles where id = auth.uid()), false);
$$;

create or replace function anvaya.is_service_role()
returns boolean
language sql
stable
as $$
  select coalesce(auth.role(), '') = 'service_role';
$$;

create or replace function anvaya.is_privileged()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select anvaya.is_service_role() or anvaya.is_admin();
$$;

comment on function anvaya.is_privileged() is
  'True for the backend service role and for admins. Used by the column guards that stop a browser session from moving a report through its lifecycle by hand.';

create or replace function anvaya.is_definer_context(p_relid oid)
returns boolean
language sql
stable
as $$
  select current_user = (
    select r.rolname
    from pg_class c
    join pg_roles r on r.oid = c.relowner
    where c.oid = p_relid
  );
$$;

comment on function anvaya.is_definer_context(oid) is
  'True when the statement is executing inside a SECURITY DEFINER function owned by the table owner (so current_user has become the owner), rather than as a direct client write. A client session is `authenticated` or `anon` and can never be the table owner, so this cannot be spoofed from the browser. Lets the sanctioned functions in this file update guarded columns while the column guards still refuse direct client writes.';

create or replace function anvaya.has_active_grant(p_doctor uuid, p_patient uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.doctor_patient_access a
    where a.doctor_id  = p_doctor
      and a.patient_id = p_patient
      and a.status     = 'active'
      and (a.expires_at is null or a.expires_at > now())
  );
$$;

comment on function anvaya.has_active_grant(uuid, uuid) is
  'The single predicate behind every doctor-facing policy: an unexpired, unrevoked grant must exist.';

create or replace function anvaya.can_access_report(p_report uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.lab_reports r
    join public.patients   p  on p.id = r.patient_id
    left join public.profiles pf on pf.id = p.profile_id
    where r.id = p_report
      and r.deleted_at is null
      and (
            pf.id = auth.uid()                                        -- owning patient
         or anvaya.is_admin()                                         -- administrator
         or exists (                                                  -- authorised clinician
              select 1
              from public.doctors d
              where d.profile_id = auth.uid()
                and anvaya.has_active_grant(d.id, p.id)
            )
      )
  );
$$;

comment on function anvaya.can_access_report(uuid) is
  'Owner, authorised reviewer, or admin — and never for a soft-deleted report. Used by the RLS policies in 0018.';

create or replace function anvaya.report_patient(p_report uuid)
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select patient_id from public.lab_reports where id = p_report;
$$;

create or replace function anvaya.test_result_report(p_test_result uuid)
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select report_id from public.test_results where id = p_test_result;
$$;

create or replace function anvaya.has_active_consent(p_patient uuid, p_purpose anvaya_consent_purpose)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  -- Append-only semantics: the MOST RECENT decision for this purpose is the one
  -- in force. A withdrawal is a newer row with status 'withdrawn', so it
  -- supersedes the earlier grant without anyone having to edit history.
  select exists (
    select 1
    from (
      select c.status, c.expires_at
      from public.patient_consents c
      where c.patient_id = p_patient
        and c.purpose    = p_purpose
      order by c.granted_at desc, c.id desc
      limit 1
    ) latest
    where latest.status = 'granted'
      and (latest.expires_at is null or latest.expires_at > now())
  );
$$;

comment on function anvaya.has_active_consent(uuid, anvaya_consent_purpose) is
  'Consent gate for the pipeline. The processing worker MUST call this before any stage that touches the model; a report whose patient has withdrawn ai_explanation consent is not eligible for generation.';

-- ---------------------------------------------------------------------------
-- Audit writer
-- ---------------------------------------------------------------------------
create or replace function anvaya.write_audit(
  p_action      text,
  p_entity_type text,
  p_entity_id   text   default null,
  p_patient_id  uuid   default null,
  p_report_id   uuid   default null,
  p_outcome     text   default 'success',
  p_metadata    jsonb  default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id   bigint;
  v_ip   inet;
  v_ua   text;
begin
  begin
    v_ip := public.inet_client_addr();
  exception when others then
    v_ip := null;
  end;

  begin
    v_ua := nullif(current_setting('request.headers', true), '')::jsonb ->> 'user-agent';
  exception when others then
    v_ua := null;
  end;

  insert into public.audit_logs
    (actor_id, actor_role, action, entity_type, entity_id, patient_id, report_id, outcome, metadata, ip_address, user_agent)
  values
    (auth.uid(), anvaya.current_role(), p_action, p_entity_type, p_entity_id,
     p_patient_id, p_report_id, p_outcome, p_metadata, v_ip, v_ua)
  returning id into v_id;
  return v_id;
end;
$$;

comment on function anvaya.write_audit(text, text, text, uuid, uuid, text, jsonb) is
  'The ONLY supported way to write an audit row. The audit_seal trigger computes the hash chain; callers never touch prev_hash/row_hash.';

-- ---------------------------------------------------------------------------
-- Patient/clinician correction of a parsed value
-- ---------------------------------------------------------------------------
create or replace function anvaya.submit_value_correction(
  p_test_result_id uuid,
  p_new_value      numeric,
  p_reason         text,
  p_as_doctor      boolean default false
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_tr       public.test_results%rowtype;
  v_report   uuid;
  v_patient  uuid;
  v_doctor   uuid;
  v_source   anvaya_value_source;
  v_new_id   uuid;
begin
  select * into v_tr from public.test_results where id = p_test_result_id for update;
  if not found then
    raise exception 'anvaya: test_result % not found', p_test_result_id;
  end if;

  v_report  := v_tr.report_id;
  v_patient := anvaya.report_patient(v_report);

  -- authorisation: the owning patient (self-correction of their own upload) or
  -- an authorised clinician. Nobody else.
  if p_as_doctor then
    v_doctor := anvaya.current_doctor_id();
    if v_doctor is null or not anvaya.has_active_grant(v_doctor, v_patient) then
      perform anvaya.write_audit('access.denied', 'test_result', p_test_result_id::text, v_patient, v_report, 'denied',
                                 jsonb_build_object('reason', 'no active grant for correction'));
      raise exception 'anvaya: not authorised to correct this result';
    end if;
    v_source := 'doctor_correction';
  else
    if anvaya.current_patient_id() is distinct from v_patient and not anvaya.is_admin() then
      perform anvaya.write_audit('access.denied', 'test_result', p_test_result_id::text, v_patient, v_report, 'denied',
                                 jsonb_build_object('reason', 'not the owning patient'));
      raise exception 'anvaya: not authorised to correct this result';
    end if;
    v_source := 'patient_correction';
  end if;

  if p_new_value is null then
    raise exception 'anvaya: a correction requires a value';
  end if;

  update public.test_results
     set corrected_value   = p_new_value,
         corrected_by      = auth.uid(),
         corrected_at      = now(),
         correction_reason = p_reason,
         value_source      = v_source
   where id = p_test_result_id;

  perform anvaya.write_audit('result.corrected', 'test_result', p_test_result_id::text, v_patient, v_report, 'success',
                             jsonb_build_object(
                               'from', v_tr.original_value,
                               'to',   p_new_value,
                               'by',   v_source));

  -- Return the CURRENT authoritative validation, so the caller can re-run the
  -- deterministic engine against the corrected value. Note what this function
  -- does NOT do: it never writes a status. Classification stays with
  -- validation_results.
  v_new_id := v_tr.current_validation_id;
  return v_new_id;
end;
$$;

comment on function anvaya.submit_value_correction(uuid, numeric, text, boolean) is
  'The only write path onto test_results correction columns. Writes the audit row in the same transaction. Deliberately does NOT set any status — the caller must re-run the deterministic engine, which appends a new validation_results row.';

-- ---------------------------------------------------------------------------
-- Review state machine
-- ---------------------------------------------------------------------------
create or replace function anvaya.set_review_status(
  p_review_id uuid,
  p_new_status anvaya_review_status,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_rev     public.doctor_reviews%rowtype;
  v_doctor  uuid;
  v_patient uuid;
  v_action  text;
  v_ok      boolean;
begin
  select * into v_rev from public.doctor_reviews where id = p_review_id for update;
  if not found then
    raise exception 'anvaya: review % not found', p_review_id;
  end if;

  v_doctor  := anvaya.current_doctor_id();
  v_patient := anvaya.report_patient(v_rev.report_id);

  -- A patient must never be able to drive a review transition.
  if v_doctor is null or v_doctor <> v_rev.doctor_id then
    perform anvaya.write_audit('access.denied', 'doctor_review', p_review_id::text, v_patient, v_rev.report_id, 'denied',
                               jsonb_build_object('attempted_status', p_new_status));
    raise exception 'anvaya: only the assigned doctor may change this review';
  end if;
  if not anvaya.has_active_grant(v_doctor, v_patient) then
    raise exception 'anvaya: reviewer no longer has access to this patient';
  end if;

  -- permitted transitions
  v_ok := case
    when v_rev.status = 'draft'          and p_new_status in ('pending_review', 'withdrawn')             then true
    when v_rev.status = 'pending_review' and p_new_status in ('approved', 'needs_edit', 'withdrawn')     then true
    when v_rev.status = 'needs_edit'     and p_new_status in ('pending_review', 'withdrawn')             then true
    when v_rev.status = 'approved'       and p_new_status = 'withdrawn'                                  then true
    else false
  end;

  if not v_ok then
    raise exception 'anvaya: illegal review transition % -> %', v_rev.status, p_new_status;
  end if;

  if p_new_status = 'needs_edit' and p_reason is null then
    raise exception 'anvaya: needs_edit requires a reason';
  end if;

  update public.doctor_reviews
     set previous_status  = v_rev.status,
         status           = p_new_status,
         opened_at        = coalesce(opened_at, now()),
         decision_at      = case when p_new_status in ('approved', 'needs_edit', 'withdrawn') then now() else decision_at end,
         signed_at        = case when p_new_status = 'approved' then coalesce(signed_at, now()) else signed_at end,
         rejection_reason = case when p_new_status = 'needs_edit' then p_reason else rejection_reason end
   where id = p_review_id;

  v_action := case p_new_status
                when 'approved'     then 'review.approved'
                when 'needs_edit'   then 'review.rejected'
                when 'pending_review' then 'review.opened'
                when 'withdrawn'    then 'review.rejected'
                else 'review.opened'
              end;

  perform anvaya.write_audit(v_action, 'doctor_review', p_review_id::text, v_patient, v_rev.report_id, 'success',
                             jsonb_build_object('from', v_rev.status, 'to', p_new_status));

  update public.lab_reports
     set status = case when p_new_status = 'pending_review' then 'in_review'::anvaya_report_status else status end
   where id = v_rev.report_id and status = 'analysed';
end;
$$;

comment on function anvaya.set_review_status(uuid, anvaya_review_status, text) is
  'Enforces draft -> pending_review -> (approved | needs_edit) and refuses everything else, including any attempt by the owning patient. `released` is NOT reachable here: release is a separate, explicitly audited act (anvaya.release_report).';

-- ---------------------------------------------------------------------------
-- Release: the only path to a patient-facing report
-- ---------------------------------------------------------------------------
create or replace function anvaya.release_report(
  p_report_id  uuid,
  p_version_id uuid,
  p_review_id  uuid default null,
  p_channel    text default 'app'
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_review  public.doctor_reviews%rowtype;
  v_patient uuid;
  v_doctor  uuid;
  v_prev    public.report_releases%rowtype;
  v_new     uuid;
begin
  select patient_id into v_patient from public.lab_reports where id = p_report_id and deleted_at is null;
  if v_patient is null then
    raise exception 'anvaya: report % not found or deleted', p_report_id;
  end if;

  if not exists (select 1 from public.report_versions where id = p_version_id and report_id = p_report_id) then
    raise exception 'anvaya: version % does not belong to report %', p_version_id, p_report_id;
  end if;

  -- the version must carry an APPROVED review by a clinician
  if p_review_id is null then
    select * into v_review
    from public.doctor_reviews
    where report_id = p_report_id and report_version_id = p_version_id and status = 'approved'
    order by decision_at desc nulls last
    limit 1;
    if not found then
      raise exception 'anvaya: no approved review exists for this report version — cannot release';
    end if;
  else
    select * into v_review from public.doctor_reviews where id = p_review_id;
    if not found or v_review.report_version_id <> p_version_id or v_review.status <> 'approved' then
      raise exception 'anvaya: review % is not an approved review of this version', p_review_id;
    end if;
  end if;

  -- only that clinician (or an admin) may release
  v_doctor := anvaya.current_doctor_id();
  if v_doctor is distinct from v_review.doctor_id and not anvaya.is_admin() then
    perform anvaya.write_audit('access.denied', 'report_release', p_report_id::text, v_patient, p_report_id, 'denied',
                               jsonb_build_object('reason', 'releaser is not the approving clinician'));
    raise exception 'anvaya: only the approving clinician may release this report';
  end if;

  -- retire any previous active release
  select * into v_prev from public.report_releases
   where report_id = p_report_id and is_active for update;
  if found then
    update public.report_releases
       set is_active = false, superseded_at = now(), superseded_by = null
     where id = v_prev.id;
  end if;

  insert into public.report_releases
    (report_id, report_version_id, review_id, released_by, release_channel)
  values
    (p_report_id, p_version_id, v_review.id, coalesce(auth.uid(), v_review.doctor_id), p_channel)
  returning id into v_new;

  update public.doctor_reviews set status = 'released' where id = v_review.id and status = 'approved';
  update public.lab_reports set status = 'released' where id = p_report_id;

  perform anvaya.write_audit('report.released', 'report_release', v_new::text, v_patient, p_report_id, 'success',
                             jsonb_build_object('version_id', p_version_id, 'review_id', v_review.id));

  return v_new;
end;
$$;

comment on function anvaya.release_report(uuid, uuid, uuid, text) is
  'The ONLY way a report becomes patient-facing. Refuses to run unless the version has an approved clinician review, and refuses to run for anyone other than that clinician. Supersedes the previous active release rather than deleting it.';

-- ---------------------------------------------------------------------------
-- Erasure
-- ---------------------------------------------------------------------------
create or replace function anvaya.hard_delete_report(
  p_report_id uuid,
  p_reason    text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_patient      uuid;
  v_allow_delete text;
begin
  select patient_id into v_patient from public.lab_reports where id = p_report_id;
  if v_patient is null then
    raise exception 'anvaya: report % not found', p_report_id;
  end if;

  -- Authorisation: the owning patient, or an admin acting on a deletion request.
  if anvaya.current_patient_id() is distinct from v_patient and not anvaya.is_admin() then
    perform anvaya.write_audit('access.denied', 'lab_report', p_report_id::text, v_patient, p_report_id, 'denied',
                               jsonb_build_object('reason', 'erasure attempted by non-owner'));
    raise exception 'anvaya: not authorised to erase this report';
  end if;

  -- Audit BEFORE destruction, so the fact survives the data.
  perform anvaya.write_audit('report.deleted', 'lab_report', p_report_id::text, v_patient, p_report_id, 'success',
                             jsonb_build_object('mode', 'hard_delete', 'reason', p_reason));

  -- Open the sanctioned-erasure window for the remainder of this transaction.
  -- Without it the append-only guards would (correctly) refuse the deletes
  -- below. It is transaction-local, so it cannot outlive this call.
  perform set_config('anvaya.erasure_in_progress', 'on', true);

  -- Dependency-ordered destruction. Nothing here relies on a blind CASCADE from
  -- patients: medical rows are RESTRICT-linked precisely so this ordering is
  -- explicit and reviewable.
  delete from public.report_releases      where report_id = p_report_id;
  delete from public.doctor_reviews       where report_id = p_report_id;
  delete from public.report_versions      where report_id = p_report_id;
  delete from public.ai_explanations      where subject_report_id = p_report_id;
  delete from public.report_patterns      where report_id = p_report_id;
  delete from public.report_files         where report_id = p_report_id;
  delete from public.anonymization_records where lab_report_id = p_report_id;
  delete from public.ocr_results          where report_id = p_report_id;
  delete from public.report_processing_jobs where report_id = p_report_id;

  -- validation_results is RESTRICT-linked to test_results, so it goes first;
  -- deleting test_results then cascades to its ai_explanations and citations.
  delete from public.validation_results
   where test_result_id in (select id from public.test_results where report_id = p_report_id);
  delete from public.test_results         where report_id = p_report_id;

  delete from public.lab_reports          where id = p_report_id;

  -- Storage objects live outside the database; remove them by prefix so no
  -- orphaned PHI remains in a bucket. Same {patient_id}/{report_id}/ convention
  -- the storage policies in 0019 rely on.
  --
  -- Supabase Storage attaches a statement-level BEFORE DELETE trigger to
  -- storage.objects (supabase/storage tenant migration 0055-prevent-direct-deletes)
  -- that refuses any direct delete unless the transaction sets
  -- storage.allow_delete_query = 'true'. That is the platform's sanctioned
  -- override for precisely this case — a deliberate, authorised, audited
  -- erasure — and it is the only way to make GDPR erasure actually reach the
  -- object store from the database. It is scoped as narrowly as the platform
  -- allows:
  --   * transaction-local (is_local => true), so it cannot outlive this call;
  --   * set inside a SECURITY DEFINER function that already authorises against
  --     auth.uid(), so a caller can only open it for its own report;
  --   * restored immediately after the delete, so nothing else in the same
  --     transaction inherits it.
  -- The alternative — dropping this delete — would leave the report's original
  -- scan, its OCR dump and its exports sitting in a bucket after the patient
  -- had exercised their right to erasure. That is the worse failure.
  if to_regclass('storage.objects') is not null then
    v_allow_delete := current_setting('storage.allow_delete_query', true);
    perform set_config('storage.allow_delete_query', 'true', true);

    delete from storage.objects
     where bucket_id in ('report-originals', 'report-processed', 'report-exports', 'voice-audio', 'consent-evidence')
       and (storage.foldername(name))[1] = v_patient::text
       and (storage.foldername(name))[2] = p_report_id::text;

    perform set_config('storage.allow_delete_query', coalesce(v_allow_delete, 'false'), true);
  end if;
end;
$$;

comment on function anvaya.hard_delete_report(uuid, text) is
  'True erasure of one report: writes the audit record first, then destroys clinical rows in explicit dependency order and removes the storage objects. Audit rows survive (they are compliance records, not PHI).';

create or replace function anvaya.hard_delete_patient(
  p_patient_id uuid,
  p_reason     text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_report record;
begin
  if anvaya.current_patient_id() is distinct from p_patient_id and not anvaya.is_admin() then
    perform anvaya.write_audit('access.denied', 'patients', p_patient_id::text, p_patient_id, null, 'denied',
                               jsonb_build_object('reason', 'account erasure attempted by non-owner'));
    raise exception 'anvaya: not authorised to erase this account';
  end if;

  perform set_config('anvaya.erasure_in_progress', 'on', true);

  for v_report in select id from public.lab_reports where patient_id = p_patient_id
  loop
    perform anvaya.hard_delete_report(v_report.id, p_reason);
  end loop;

  delete from public.voice_sessions    where patient_id = p_patient_id;
  delete from public.answer_feedback   where patient_id = p_patient_id;
  delete from public.patient_consents  where patient_id = p_patient_id;
  delete from public.doctor_patient_access where patient_id = p_patient_id;

  -- De-link (do not delete) the audit history: the fact that actions occurred is
  -- compliance information; the identity attached to them is not.
  update public.audit_logs set patient_id = null where patient_id = p_patient_id;

  delete from public.patients where id = p_patient_id;

  -- Written last, with no patient identifier attached, so the record that an
  -- erasure happened survives without re-identifying the person.
  perform anvaya.write_audit('deletion.completed', 'patients', null, null, null, 'success',
                             jsonb_build_object('mode', 'account_erasure', 'reason', p_reason));

  perform set_config('anvaya.erasure_in_progress', 'off', true);
end;
$$;

comment on function anvaya.hard_delete_patient(uuid, text) is
  'Account erasure. Destroys clinical data and consents, de-links the audit trail rather than deleting it, and removes the patient row. Retains exactly the minimal compliance record.';

-- <<< END db/migrations/0017_functions.sql
