-- ============================================================================
-- Anvaya Supabase SQL Editor part 05 of 05
-- Run the files in db/sql_editor_parts in numeric order, one at a time.
-- This file is generated by concatenating the ordered migrations listed below.
-- It is idempotent: if a part fails after partially running, fix the error and
-- re-run the same part before continuing to the next number.
--
-- Includes:
--   - db/migrations/0019_storage.sql
--   - db/migrations/0020_views.sql
--   - db/migrations/0021_seed_catalog.sql
-- ============================================================================

-- >>> BEGIN db/migrations/0019_storage.sql
-- ============================================================================
-- Anvaya / Rxanvaya — Supabase migration 0019
-- Supabase Storage buckets, the access predicate, and the object policies
-- ----------------------------------------------------------------------------
-- Purpose   : Keep every byte of medical data in PRIVATE buckets, addressed by
--             a predictable key convention, with object-level policies that
--             agree with the database RLS in 0018.
-- Depends on: 0004, 0017, 0018 (anvaya.current_patient_id / has_active_grant /
--             grants on the anvaya schema)
-- Fresh safe: YES (bucket inserts are ON CONFLICT DO NOTHING; the policy block
--             drops before it creates and is skipped entirely when the caller
--             is not allowed to touch storage.objects)
--
-- ---------------------------------------------------------------------------
-- THE REAL-SUPABASE CONSTRAINT THIS FILE IS BUILT AROUND — READ BEFORE EDITING
-- ---------------------------------------------------------------------------
-- storage.buckets and storage.objects are OWNED BY supabase_storage_admin, and
-- since Supabase platform migration 20250421084701_revoke_admin_roles_from_postgres
-- the role the SQL Editor connects as (`postgres`) is NO LONGER A MEMBER of that
-- role. It is therefore not treated as the owner of those tables.
--
-- PostgreSQL requires OWNERSHIP — not merely a table-level GRANT — for each of:
--
--   alter table storage.objects enable row level security
--       -> ERROR 42501: must be owner of table objects
--   alter table storage.objects force  row level security
--       -> ERROR 42501: must be owner of table objects
--   create index ... on storage.objects
--       -> ERROR 42501: must be owner of table objects
--   create policy ... on storage.objects
--       -> ERROR 42501: must be owner of table objects
--   drop policy ... on storage.objects            (when the policy exists)
--       -> ERROR 42501: must be owner of relation objects
--   comment on policy ... on storage.objects
--       -> ERROR 42501: must be owner of relation objects
--
-- Supabase DOES grant `grant all on storage.buckets, storage.objects to postgres
-- with grant option`, which is why DML works — but GRANT ALL covers DML only,
-- never DDL. Every ownership-requiring statement is gone from this file or sits
-- behind the capability probe in the policy block.
--
-- WHAT THIS FILE DOES
--   1. Creates the five PRIVATE buckets            (DML — always permitted)
--   2. Asserts none of them is public              (fails the migration if so)
--   3. Creates anvaya.may_access_patient_prefix()  (our schema — always permitted)
--   4. Creates the 15 object policies, but ONLY if the current role actually
--      owns storage.objects; otherwise it says so and prints what to do instead
--
-- WHAT THIS FILE DELIBERATELY DOES NOT DO
--   * It never runs ALTER TABLE against storage.objects or storage.buckets.
--     Supabase's own storage migrations already enable RLS on both
--     (supabase/storage tenant 0002 for objects, tenant 0007 for buckets), and
--     re-asserting it is not ours to do.
--   * It never disables, replaces or rewrites Supabase's storage RLS.
--   * It never creates indexes, columns or triggers on Supabase's tables.
--
-- SECURITY DIRECTION OF FAILURE
--   If the policies cannot be created here, storage.objects RLS is still ON and
--   has no policy for our buckets — so `authenticated` can read, upload and
--   delete NOTHING. The app cannot use storage yet, but nothing is exposed.
--   Adding the policies in the dashboard is the step that OPENS the narrow,
--   prefix-scoped path; it is never the step that closes a hole.
--
-- KEY CONVENTION
--   {patient_id}/{report_id}/{kind}-{n}.{ext}
--   Prefixing with patient_id makes per-patient erasure a single prefix delete,
--   which anvaya.hard_delete_report() relies on.
--
-- WHAT BELONGS IN STORAGE, NOT IN POSTGRES
--   * the original photo / PDF as uploaded
--   * the processed (deskewed, contrast-fixed) image
--   * full OCR dumps, if retained
--   * exported patient and doctor PDFs
--   * generated TTS audio and captured question audio
--   * consent evidence recordings and signature images
--   PostgreSQL keeps only bucket + path + checksum + size (report_files).
--
-- NOTHING HERE IS PUBLIC. A public bucket serving lab reports would defeat the
-- entire RLS model, because a signed URL is not required to read a public object.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Buckets
-- ---------------------------------------------------------------------------
-- DML on storage.buckets is explicitly granted to the SQL Editor role, so this
-- is the one part of storage setup that always runs from the SQL Editor.
-- `on conflict do nothing` (not `on conflict (id)`) so a pre-existing bucket
-- that happens to collide on the unique `name` index is skipped rather than
-- aborting the whole migration.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('report-originals', 'report-originals', false, 26214400,
    array['image/jpeg','image/png','image/webp','image/heic','application/pdf','text/csv']),
  ('report-processed', 'report-processed', false, 26214400,
    array['image/jpeg','image/png','image/webp','application/json']),
  ('report-exports',   'report-exports',   false, 15728640,
    array['application/pdf','image/png']),
  ('voice-audio',      'voice-audio',      false, 10485760,
    array['audio/webm','audio/mpeg','audio/mp4','audio/ogg','audio/wav']),
  ('consent-evidence', 'consent-evidence', false, 10485760,
    array['audio/webm','audio/mpeg','audio/wav','image/png','image/jpeg','application/pdf'])
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- 2. Fail loudly rather than ship a public medical bucket
-- ---------------------------------------------------------------------------
do $do$
declare
  v_ids   text[] := array['report-originals','report-processed','report-exports',
                          'voice-audio','consent-evidence'];
  v_bad   text;
  v_found int;
begin
  select string_agg(id, ', ' order by id) into v_bad
    from storage.buckets
   where id = any (v_ids)
     and public is true;
  if v_bad is not null then
    raise exception
      'anvaya 0019: refusing to continue — these Anvaya buckets are PUBLIC: %. A public bucket serving lab reports defeats the RLS model, because reading a public object needs no signed URL.', v_bad;
  end if;

  select count(*) into v_found from storage.buckets where id = any (v_ids);
  if v_found <> 5 then
    raise exception 'anvaya 0019: expected 5 Anvaya buckets, found %', v_found;
  end if;
end
$do$;

-- ---------------------------------------------------------------------------
-- 3. Shared predicate: may the caller touch objects under this patient prefix?
-- ---------------------------------------------------------------------------
-- Created in OUR schema, so it never touches the ownership of a Supabase table.
create or replace function anvaya.may_access_patient_prefix(p_object_name text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select (
    (storage.foldername(p_object_name))[1] = anvaya.current_patient_id()::text
    or anvaya.is_admin()
    or exists (
      select 1
      from public.patients p
      where p.id::text = (storage.foldername(p_object_name))[1]
        and exists (
          select 1 from public.doctors d
          where d.profile_id = auth.uid()
            and anvaya.has_active_grant(d.id, p.id)
        )
    )
  );
$$;

comment on function anvaya.may_access_patient_prefix(text) is
  'One predicate behind every storage policy: the owning patient, an authorised clinician, or an admin. Uses the same grant table as the database RLS so the two can never disagree.';

-- 0018 revokes EXECUTE on the anvaya schema from anon for every function that
-- existed at the time. This one is created later, so the revocation is repeated
-- explicitly and `authenticated` / `service_role` are granted it outright,
-- because a storage.objects policy is evaluated as the querying role.
grant  execute on function anvaya.may_access_patient_prefix(text) to authenticated, service_role;
revoke execute on function anvaya.may_access_patient_prefix(text) from anon, public;

-- ---------------------------------------------------------------------------
-- 4. Object policies — behind a capability probe
-- ---------------------------------------------------------------------------
-- pg_has_role(current_user, <table owner>, 'USAGE') is the SQL-visible form of
-- the exact test PostgreSQL runs before CREATE POLICY / ALTER TABLE
-- (object_ownercheck -> has_privs_of_role). When it is false, every policy
-- statement below would abort with SQLSTATE 42501, so we do not run them and we
-- say exactly what to do instead.
do $do$
declare
  r         record;
  v_owner   text;
  v_can_ddl boolean;
  v_created int := 0;
begin
  select c.relowner::regrole::text into v_owner
    from pg_class c
   where c.oid = 'storage.objects'::regclass;

  v_can_ddl := pg_has_role(
    current_user,
    (select relowner from pg_class where oid = 'storage.objects'::regclass),
    'USAGE');

  if not v_can_ddl then
    raise notice
      'anvaya 0019: current_user "%" does not own storage.objects (owner: %), so CREATE POLICY / DROP POLICY would fail with SQLSTATE 42501. Skipping all 15 object policies. The 5 buckets are private and storage.objects RLS is ON, so storage is CLOSED BY DEFAULT — nothing can be read, uploaded or deleted yet. Create the policies in the dashboard: Storage -> Policies -> storage.objects -> For full customization, one policy per bucket per command, USING / WITH CHECK: bucket_id = ''<bucket>'' and anvaya.may_access_patient_prefix(name).',
      current_user, v_owner;
    return;
  end if;

  for r in
    select b.bucket, k.cmd, k.suffix
      from (values ('report-originals'), ('report-processed'), ('report-exports'),
                   ('voice-audio'),     ('consent-evidence')) as b(bucket)
     cross join (values ('select', 'read'),
                        ('insert', 'insert'),
                        ('delete', 'delete'))                as k(cmd, suffix)
  loop
    execute format('drop policy if exists %I on storage.objects',
                   r.bucket || '_' || r.suffix);

    if r.cmd = 'insert' then
      execute format($f$
        create policy %I on storage.objects
          for insert to authenticated
          with check (bucket_id = %L and anvaya.may_access_patient_prefix(name))
      $f$, r.bucket || '_' || r.suffix, r.bucket);
    else
      execute format($f$
        create policy %I on storage.objects
          for %s to authenticated
          using (bucket_id = %L and anvaya.may_access_patient_prefix(name))
      $f$, r.bucket || '_' || r.suffix, r.cmd, r.bucket);
    end if;

    v_created := v_created + 1;
  end loop;

  raise notice 'anvaya 0019: created % object policies on storage.objects.', v_created;
end
$do$;

-- ---------------------------------------------------------------------------
-- 5. Self-check, so the run tells you where storage ended up either way
-- ---------------------------------------------------------------------------
-- Reads pg_policies only — no DDL, so it is always permitted. A count below 15
-- means the policies still have to be added in the dashboard (see the NOTICE
-- above). It is a NOTICE, not an exception, because a zero here is the expected
-- and SAFE state on a stock Supabase project.
do $do$
declare
  v_present int;
begin
  select count(*) into v_present
    from pg_policies
   where schemaname = 'storage'
     and tablename  = 'objects'
     and policyname in ('report-originals_read','report-originals_insert','report-originals_delete',
                        'report-processed_read','report-processed_insert','report-processed_delete',
                        'report-exports_read',  'report-exports_insert',  'report-exports_delete',
                        'voice-audio_read',     'voice-audio_insert',     'voice-audio_delete',
                        'consent-evidence_read','consent-evidence_insert','consent-evidence_delete');

  if v_present < 15 then
    raise notice
      'anvaya 0019: % of 15 storage.objects policies present. Storage stays closed until the rest are added (Storage -> Policies -> storage.objects).',
      v_present;
  else
    raise notice 'anvaya 0019: all 15 storage.objects policies present.';
  end if;
end
$do$;

-- NOTE ON COMMENT ON POLICY
--   An earlier revision of this migration ended with
--       comment on policy "report-originals_read" on storage.objects is '...';
--   COMMENT ON POLICY is a table-ownership operation, so on a real project it
--   fails with 42501 and — worse — it only fails when the policy exists, which
--   makes the migration pass on a fresh project and break on re-run. It is
--   removed; the same sentence lives in the comment on
--   anvaya.may_access_patient_prefix() above, which we do own.

-- <<< END db/migrations/0019_storage.sql

-- >>> BEGIN db/migrations/0020_views.sql
-- ============================================================================
-- Anvaya / Rxanvaya — Supabase migration 0020
-- Read models (views) for the app's actual query patterns
-- ----------------------------------------------------------------------------
-- Purpose   : Give the UI stable, RLS-respecting read shapes that mirror the
--             TypeScript interfaces it already renders, so wiring the app to the
--             database is a change of data source rather than a redesign.
-- Depends on: 0006-0016
-- Fresh safe: YES (create or replace / drop if exists)
--
-- These are plain views, not materialised: they inherit the RLS of the tables
-- underneath, so they cannot become a side channel around 0018.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Report list / summary  ->  src/lib/data.ts Report { id, date, testsCount,
--                                                     attention, entries[] }
-- ---------------------------------------------------------------------------
create or replace view public.v_report_summary as
select
  r.id,
  r.patient_id,
  r.legacy_code,
  r.status,
  r.collected_on,
  r.lab_name,
  r.report_number,
  r.upload_channel,
  r.created_at,
  r.updated_at,
  count(t.id)                                                        as tests_count,
  -- "needs attention" = anything the deterministic engine called high, low or
  -- critical. This is a DERIVED number, not a stored one: the hardcoded
  -- `attention` values in src/lib/data.ts do not agree with their own entries
  -- (jun26 says 3 but has 6 high/low rows; aug26 says 4 but has 3), so the
  -- schema recomputes it from the source of truth instead of persisting it.
  count(*) filter (where v.computed_status in ('high', 'low', 'critical'))  as attention_count,
  count(*) filter (where v.computed_status = 'critical')                    as critical_count,
  count(*) filter (where v.computed_status = 'borderline')                  as borderline_count,
  count(*) filter (where v.computed_status = 'normal')                      as normal_count,
  bool_or(v.is_critical)                                                    as has_critical,
  exists (select 1 from public.report_releases rel
           where rel.report_id = r.id and rel.is_active)                    as is_released
from public.lab_reports r
left join public.test_results t on t.report_id = r.id
left join public.validation_results v on v.id = t.current_validation_id
where r.deleted_at is null
group by r.id;

comment on view public.v_report_summary is
  'One row per live report with derived counts. Backs the My Reports / Trends / Dashboard screens.';

-- ---------------------------------------------------------------------------
-- Longitudinal history  ->  trendSeries() / getValue() in src/lib/data.ts
-- ---------------------------------------------------------------------------
create or replace view public.v_test_history as
select
  r.patient_id,
  t.lab_test_id,
  c.code                              as test_code,
  c.name_en,
  r.id                                as report_id,
  r.legacy_code,
  r.collected_on,
  coalesce(t.corrected_value, t.value) as effective_value,
  t.unit,
  v.computed_status,
  v.is_critical,
  v.ref_low,
  v.ref_high,
  t.ocr_confidence,
  t.corrected_at is not null          as was_corrected
from public.test_results t
join public.lab_reports r       on r.id = t.report_id and r.deleted_at is null
left join public.lab_test_catalog c on c.id = t.lab_test_id
left join public.validation_results v on v.id = t.current_validation_id
where t.lab_test_id is not null;

comment on view public.v_test_history is
  'The trend query: every measurement of one test for one patient across all their reports, newest-last when ordered by collected_on. Indexed by test_results_trend_idx + reports_patient_history_idx.';

-- ---------------------------------------------------------------------------
-- Latest result per test for a patient  ->  latestEntry() in src/lib/data.ts
-- ---------------------------------------------------------------------------
create or replace view public.v_patient_latest_results as
select distinct on (h.patient_id, h.lab_test_id)
  h.patient_id, h.lab_test_id, h.test_code, h.name_en, h.report_id,
  h.collected_on, h.effective_value, h.unit, h.computed_status, h.is_critical
from public.v_test_history h
order by h.patient_id, h.lab_test_id, h.collected_on desc;

comment on view public.v_patient_latest_results is
  'DISTINCT ON gives the most recent measurement of each test per patient without a correlated subquery.';

-- ---------------------------------------------------------------------------
-- Doctor review queue
-- ---------------------------------------------------------------------------
create or replace view public.v_review_queue as
select
  dr.id                as review_id,
  dr.report_id,
  dr.report_version_id,
  rv.version_no,
  dr.doctor_id,
  d.full_name          as doctor_name,
  dr.status,
  dr.assigned_at,
  dr.opened_at,
  dr.decision_at,
  r.patient_id,
  p.full_name          as patient_name,
  r.collected_on,
  r.status             as report_status,
  s.attention_count,
  s.has_critical
from public.doctor_reviews dr
join public.doctors d        on d.id = dr.doctor_id
join public.lab_reports r    on r.id = dr.report_id
join public.patients p       on p.id = r.patient_id
join public.report_versions rv on rv.id = dr.report_version_id
left join public.v_report_summary s on s.id = r.id
where r.deleted_at is null;

comment on view public.v_review_queue is
  'The clinician worklist. Filter on status = ''pending_review'' and order by assigned_at for the queue; RLS on doctor_reviews already limits rows to the assigned doctor.';

-- ---------------------------------------------------------------------------
-- Citation trail  ->  "what source supported this statement?"
-- ---------------------------------------------------------------------------
create or replace view public.v_citation_trail as
select
  e.id                 as explanation_id,
  e.language,
  e.reading_level,
  e.subject_test_result_id,
  e.subject_report_pattern_id,
  e.subject_report_id,
  g.model,
  g.model_version,
  g.trust_score,
  g.trust_level,
  g.model_confidence,
  g.retrieval_similarity,
  ec.citation_index,
  ec.rank,
  ec.similarity,
  ec.quoted_text,
  ch.id                as chunk_id,
  ch.seq               as chunk_seq,
  ch.heading           as chunk_heading,
  ch.content           as chunk_content,
  doc.version          as document_version,
  doc.retrieved_at,
  src.code             as source_code,
  src.title            as source_title,
  src.publisher,
  src.country,
  src.url              as source_url
from public.explanation_citations ec
join public.ai_explanations e on e.id = ec.explanation_id
join public.rag_chunks ch     on ch.id = ec.rag_chunk_id
join public.rag_documents doc on doc.id = ch.document_id
join public.rag_sources src   on src.id = doc.rag_source_id
left join public.ai_generations g on g.id = e.generation_id;

comment on view public.v_citation_trail is
  'Full provenance chain for any statement shown to a patient: explanation -> chunk -> document -> publisher, with the retrieval rank and similarity that earned the citation.';

-- ---------------------------------------------------------------------------
-- Processing status  ->  src/app/processing/page.tsx stage list
-- ---------------------------------------------------------------------------
create or replace view public.v_report_pipeline as
select
  j.report_id,
  j.stage,
  j.status,
  j.attempt,
  j.progress_pct,
  j.started_at,
  j.finished_at,
  j.error_code,
  j.error_message,
  row_number() over (partition by j.report_id, j.stage order by j.attempt desc) as attempt_rank
from public.report_processing_jobs j;

comment on view public.v_report_pipeline is
  'Per-report stage progress. attempt_rank = 1 is the latest attempt for each stage, which is what the progress screen should render.';

grant select on public.v_report_summary,
                public.v_test_history,
                public.v_patient_latest_results,
                public.v_review_queue,
                public.v_citation_trail,
                public.v_report_pipeline
  to authenticated, service_role;

-- <<< END db/migrations/0020_views.sql

-- >>> BEGIN db/migrations/0021_seed_catalog.sql
-- ============================================================================
-- Anvaya / Rxanvaya — Supabase migration 0021
-- Seed: test catalogue, aliases, reference ranges, RAG sources,
--       pattern templates, default rule, consent policy
-- ----------------------------------------------------------------------------
-- Purpose   : Populate the non-PHI reference data the pipeline needs on day one,
--             transcribed from src/lib/data.ts so the database and the existing
--             UI agree on identifiers and units.
-- Depends on: 0005, 0006, 0013
-- Fresh safe: YES — fully idempotent (ON CONFLICT DO NOTHING throughout), so it
--             can be re-run without duplicating rows.
--
-- !!! TWO SEEDED VALUES ARE PLACEHOLDERS THAT NEED CLINICAL SIGN-OFF !!!
--
--   1. reference_ranges.borderline_frac = 0.10
--      The app renders a 5th status, "borderline" / "Needs attention", but no
--      band width is defined anywhere in the code, and the demo data is
--      internally inconsistent about it (triglycerides 205 mg/dL is labelled
--      "borderline" while 170 mg/dL is "high", both against ref_high 150;
--      glucose 104/116/126 mg/dL are all "borderline" against ref 70-99).
--      0.10 (10% of the reference span beyond the bound) is a reasonable
--      starting default, NOT a clinical decision. Replace it per test once a
--      clinician has agreed the bands.
--
--   2. critical_low / critical_high are seeded NULL for every test.
--      Panic values must come from an authoritative source (ICMR / the
--      reporting laboratory), not from this file. src/lib/data.ts CRITICAL_DEMO
--      shows potassium 6.4 mmol/L flagged as urgent, but that is fictional demo
--      content and is not a citable threshold. The mechanism is fully wired —
--      anvaya.classify_value() honours critical bounds and validation_results
--      records them — so enabling it is a data change, not a schema change.
--
--   The ranges below are the ones PRINTED IN THE DEMO APP (src/lib/data.ts
--   TestDef.ref). They are seeded under source code 'APP_DEMO' so they are
--   clearly attributable and easy to supersede with ICMR/WHO rows, which win
--   ties via reference_range_sources.authority_rank.
-- ============================================================================

-- ------------------------------- sources -----------------------------------
insert into public.reference_range_sources (code, name, country, url, authority_rank)
values
  ('ICMR',     'Indian Council of Medical Research', 'India', 'https://www.icmr.nic.in/', 1),
  ('WHO',      'World Health Organization',          'International', 'https://www.who.int/', 2),
  ('LAB',      'Reporting laboratory (printed range)', 'India', null, 3),
  ('APP_DEMO', 'Ranges printed in the Anvaya prototype', 'India', null, 90)
on conflict (code) do nothing;

-- ---------------------------- test catalogue --------------------------------
-- codes, units and names are transcribed from the 14 TestDef records in
-- src/lib/data.ts so /test/[id] route params keep resolving unchanged.
insert into public.lab_test_catalog
  (code, name_en, name_hi, simple_name_en, simple_name_hi, default_unit, category, icon_key, sort_order)
values
  ('hemoglobin',   'Hemoglobin',        'हीमोग्लोबिन',        'Blood — haemoglobin', 'ख़ून — हीमोग्लोबिन', 'g/dL',      'haematology', 'droplets',    1),
  ('hba1c',        'HbA1c',             'HbA1c (एचबीए1सी)',   'Average blood sugar', 'औसत ब्लड शुगर',    '%',         'glycaemia',   'activity',    2),
  ('glucose',      'Fasting Glucose',   'फ़ास्टिंग ग्लूकोज़',  'Blood sugar today',   'आज की ब्लड शुगर',  'mg/dL',     'glycaemia',   'gauge',       3),
  ('ldl',          'LDL Cholesterol',   'LDL कोलेस्ट्रॉल',     'Bad cholesterol',     'ख़राब कोलेस्ट्रॉल',  'mg/dL',     'lipid',       'heart',       4),
  ('hdl',          'HDL Cholesterol',   'HDL कोलेस्ट्रॉल',     'Good cholesterol',    'अच्छा कोलेस्ट्रॉल',  'mg/dL',     'lipid',       'heartpulse',  5),
  ('triglycerides','Triglycerides',     'ट्राइग्लिसराइड',      'Blood fats',          'ख़ून की वसा',       'mg/dL',     'lipid',       'droplet',     6),
  ('totalchol',    'Total Cholesterol', 'कुल कोलेस्ट्रॉल',     'Total cholesterol',   'कुल कोलेस्ट्रॉल',   'mg/dL',     'lipid',       'sigma',       7),
  ('creatinine',   'Creatinine',        'क्रिएटिनिन',          'Kidney function',     'किडनी की कार्यक्षमता','mg/dL',    'renal',       'filter',      8),
  ('platelets',    'Platelet Count',    'प्लेटलेट गणना',       'Clotting cells',      'ख़ून जमाने वाली कोशिकाएँ','×10³/µL','haematology','square',    9),
  ('wbc',          'WBC Count',         'डब्ल्यूबीसी गणना',    'White blood cells',   'सफ़ेद रक्त कोशिकाएँ','×10³/µL',  'haematology', 'shield',     10),
  ('mcv',          'MCV',               'MCV (लाल कोशिका आकार)','Red cell size',       'लाल कोशिका का आकार', 'fL',       'haematology', 'circledashed',11),
  ('rbc',          'RBC Count',         'RBC गणना',            'Red blood cells',     'लाल रक्त कोशिकाएँ',  'mill/µL',  'haematology', 'circle',     12),
  ('hematocrit',   'Hematocrit',        'हेमैटोक्रिट',         'Blood thickness',     'ख़ून की गाढ़ता',      '%',        'haematology', 'donut',      13),
  ('potassium',    'Potassium',         'पोटैशियम',            'Body salts — potassium','शरीर का लवण — पोटैशियम','mmol/L','electrolyte','banana',   14)
on conflict (code) do nothing;

-- --------------------------------- aliases ---------------------------------
-- The normalisation dictionary behind the "Data normalisation" pipeline stage.
insert into public.lab_test_aliases (lab_test_id, alias, language, source)
select c.id, a.alias, a.lang::anvaya_lang_code, 'manual'
from (values
  ('hemoglobin',    'Hb',            'en'),
  ('hemoglobin',    'Haemoglobin',   'en'),
  ('hemoglobin',    'HGB',           'en'),
  ('hemoglobin',    'हीमोग्लोबिन',     'hi'),
  ('hba1c',         'A1C',           'en'),
  ('hba1c',         'Glycated haemoglobin', 'en'),
  ('hba1c',         'एचबीए1सी',        'hi'),
  ('glucose',       'FBS',           'en'),
  ('glucose',       'Fasting blood sugar', 'en'),
  ('glucose',       'GLU',           'en'),
  ('glucose',       'ग्लूकोज़',         'hi'),
  ('ldl',           'LDL-C',         'en'),
  ('ldl',           'एलडीएल',          'hi'),
  ('hdl',           'HDL-C',         'en'),
  ('triglycerides', 'TG',            'en'),
  ('triglycerides', 'Trig',          'en'),
  ('totalchol',     'Total Chol',    'en'),
  ('totalchol',     'TC',            'en'),
  ('creatinine',    'Serum Creatinine', 'en'),
  ('creatinine',    'S. Creatinine', 'en'),
  ('platelets',     'PLT',           'en'),
  ('wbc',           'TLC',           'en'),
  ('wbc',           'Total leucocyte count', 'en'),
  ('mcv',           'Mean corpuscular volume', 'en'),
  ('rbc',           'RBC',           'en'),
  ('rbc',           'Erythrocyte count', 'en'),
  ('hematocrit',    'HCT',           'en'),
  ('hematocrit',    'Packed cell volume', 'en'),
  ('potassium',     'K+',            'en'),
  ('potassium',     'Serum Potassium','en')
) as a(test_code, alias, lang)
join public.lab_test_catalog c on c.code = a.test_code
on conflict (lab_test_id, lower(alias), language) do nothing;

-- --------------------------- reference ranges --------------------------------
-- ref_low / ref_high exactly as printed in src/lib/data.ts TestDef.ref.
-- An open-ended range (e.g. HbA1c "below 5.7%") stores only the bound that
-- exists, which is why both columns are nullable.
insert into public.reference_ranges
  (lab_test_id, source_id, unit, ref_low, ref_high, borderline_frac,
   applicable_sex, population, version, effective_from, is_active)
select c.id, s.id, v.unit, v.lo, v.hi, 0.10, 'any', 'adult', '1.0.0', date '2026-01-01', true
from (values
  ('hemoglobin',    'g/dL',      12.0, 16.0),
  ('hba1c',         '%',         null, 5.7),
  ('glucose',       'mg/dL',     70.0, 99.0),
  ('ldl',           'mg/dL',     null, 100.0),
  ('hdl',           'mg/dL',     40.0, null),
  ('triglycerides', 'mg/dL',     null, 150.0),
  ('totalchol',     'mg/dL',     null, 200.0),
  ('creatinine',    'mg/dL',     0.7,  1.3),
  ('platelets',     '×10³/µL',  150.0, 410.0),
  ('wbc',           '×10³/µL',    4.0,  11.0),
  ('mcv',           'fL',        80.0, 100.0),
  ('rbc',           'mill/µL',    4.5,   5.9),
  ('hematocrit',    '%',         40.0,  50.0),
  ('potassium',     'mmol/L',     3.5,   5.0)
) as v(test_code, unit, lo, hi)
join public.lab_test_catalog c on c.code = v.test_code
join public.reference_range_sources s on s.code = 'APP_DEMO'
on conflict (lab_test_id, source_id, version, unit,
             coalesce(applicable_sex, 'any'), coalesce(population, 'all'),
             effective_from) do nothing;

-- ------------------------------ clinical rule -------------------------------
insert into public.clinical_rules
  (rule_key, version, description, engine_version, params, is_active)
values
  ('range_threshold', '1.0.0',
   'Compare the effective value against the reference range in force: beyond a critical bound -> critical; beyond the reference bound by more than borderline_frac of the reference span -> high/low; inside that band -> borderline; otherwise normal.',
   'anvaya-validator-1.0.0',
   '{"evaluation_order":["critical_low","critical_high","ref_low","ref_high"],"rounding":"none"}'::jsonb,
   true)
on conflict (rule_key, version, coalesce(applies_to, '00000000-0000-0000-0000-000000000000'::uuid)) do nothing;

-- ------------------------------- RAG sources --------------------------------
-- code / title / publisher / country / url transcribed from the 5 Source records
-- in src/lib/data.ts, so /sources and TestDef.sources keep resolving.
insert into public.rag_sources (code, title, publisher, country, url)
values
  ('medlineplus-hgb', 'Hemoglobin Test',
   'MedlinePlus — U.S. National Library of Medicine', 'USA',
   'https://medlineplus.gov/lab-tests/hemoglobin-test/'),
  ('cdc-a1c', 'A1C Test for Diabetes',
   'CDC — Centers for Disease Control and Prevention', 'USA',
   'https://www.cdc.gov/diabetes/testing/'),
  ('aha-chol', 'What Your Cholesterol Levels Mean',
   'American Heart Association', 'USA',
   'https://www.heart.org/en/health-topics/cholesterol/about-cholesterol/what-your-cholesterol-levels-mean'),
  ('nhlbi-tg', 'High Blood Triglycerides',
   'NHLBI — National Heart, Lung, and Blood Institute (NIH)', 'USA',
   'https://www.nhlbi.nih.gov/health/high-blood-triglycerides'),
  ('medlineplus-creatinine', 'Creatinine Test',
   'MedlinePlus — U.S. National Library of Medicine', 'USA',
   'https://medlineplus.gov/lab-tests/creatinine-test/')
on conflict (code) do nothing;

-- ---------------------------- pattern templates -----------------------------
-- The three Pattern records in src/lib/data.ts. Titles only; the narrative is
-- produced per report and stored in ai_explanations.
insert into public.pattern_templates (code, title_en, title_hi, description)
values
  ('pattern-lipid', 'Lipid pattern',        'लिपिड पैटर्न',
   'LDL, HDL, triglycerides and total cholesterol read together rather than individually.'),
  ('pattern-blood', 'Blood-count pattern',  'रक्त-गणना पैटर्न',
   'Hemoglobin, MCV, RBC and hematocrit read together to characterise an anaemia pattern.'),
  ('pattern-sugar', 'Raised blood-sugar pattern', 'बढ़ी ब्लड शुगर पैटर्न',
   'Fasting glucose and HbA1c read together to distinguish a one-off reading from a sustained pattern.')
on conflict (code) do nothing;

-- ------------------------------ consent policy ------------------------------
insert into public.consent_policies
  (code, version, purpose, title_en, title_hi, summary_en, summary_hi,
   full_text_en, doc_hash, is_active)
select
  'anvaya_processing', '1.0.0', p.purpose, p.title_en, p.title_hi, p.summary_en, p.summary_hi,
  p.full_en,
  encode(sha256((p.purpose::text || '|' || p.full_en)::bytea), 'hex'),
  true
from (values
  ('report_parsing'::anvaya_consent_purpose,
   'Read my lab report', 'मेरी लैब रिपोर्ट पढ़ना',
   'Allow Anvaya to read the report you upload and turn it into structured test results.',
   'अनवया को आपकी अपलोड की गई रिपोर्ट पढ़कर उसे संरचित परिणामों में बदलने की अनुमति दें।',
   'Anvaya will read the report image or PDF you upload, identify the tests, values, units and the reference ranges printed on it, and store them against your account. You can correct any value it misreads.'),
  ('ai_explanation'::anvaya_consent_purpose,
   'Explain my results in simple language', 'मेरे परिणाम सरल भाषा में समझाना',
   'Allow Anvaya to generate a plain-language explanation of your results using an AI model.',
   'अनवया को AI मॉडल का उपयोग करके आपके परिणामों की सरल भाषा में व्याख्या तैयार करने की अनुमति दें।',
   'Only de-identified data is used: your name, contact details, date of birth, report number and laboratory name are removed before anything reaches the AI model. Values, units, reference ranges and your age band may be used. Every explanation is reviewed by a doctor before it reaches you.'),
  ('rag_grounding'::anvaya_consent_purpose,
   'Ground explanations in medical sources', 'व्याख्याओं को चिकित्सा स्रोतों पर आधारित करना',
   'Allow Anvaya to cite clinical guidelines and trusted health sources in your explanations.',
   'अनवया को आपकी व्याख्याओं में नैदानिक दिशानिर्देश और विश्वसनीय स्वास्थ्य स्रोतों का उद्धरण देने की अनुमति दें।',
   'Anvaya searches a curated corpus of clinical guidance and shows you which passage supported each statement, with its publisher and link.'),
  ('voice_interaction'::anvaya_consent_purpose,
   'Answer my questions by voice', 'आवाज़ से मेरे प्रश्नों का उत्तर देना',
   'Allow Anvaya to transcribe your spoken questions and read answers aloud.',
   'अनवया को आपके बोले गए प्रश्नों को लिप्यंतरित करने और उत्तर बोलकर सुनाने की अनुमति दें।',
   'Audio you record is stored privately against your account, transcribed, and answered using only your own de-identified results. You can delete a conversation at any time.'),
  ('longitudinal_trends'::anvaya_consent_purpose,
   'Compare with my earlier reports', 'मेरी पिछली रिपोर्टों से तुलना करना',
   'Allow Anvaya to compare a new report with your previous ones to show trends.',
   'अनवया को रुझान दिखाने के लिए नई रिपोर्ट की आपकी पिछली रिपोर्टों से तुलना करने की अनुमति दें।',
   'Anvaya will compare your results across your own reports over time. Trends are shown to you and to a reviewing doctor; they never change how an individual result is classified.'),
  ('doctor_review'::anvaya_consent_purpose,
   'Have a doctor review my report', 'डॉक्टर से मेरी रिपोर्ट की समीक्षा कराना',
   'Allow an authorised clinician to review your report before it is released to you.',
   'आपकी रिपोर्ट आपको देने से पहले किसी अधिकृत चिकित्सक द्वारा उसकी समीक्षा करने की अनुमति दें।',
   'Only clinicians you or your care team have authorised can see your report, and only for the period the authorisation covers. Every access is logged.')
) as p(purpose, title_en, title_hi, summary_en, summary_hi, full_en)
on conflict (code, version, purpose) do nothing;

-- <<< END db/migrations/0021_seed_catalog.sql
