// ---------------------------------------------------------------------------
// Prompt library — versioned like code, because ai_generations stores
// prompt_key, prompt_version and system_prompt_sha256 so that a later edit to
// a prompt cannot silently reinterpret answers generated by the old one.
// ---------------------------------------------------------------------------

import { createHash } from "node:crypto";
import type { LangCode } from "@/lib/data";
import type { AnonymisedPayload, ReadingLevel, RetrievedChunk } from "./types";
import { renderPayloadForPrompt } from "./anonymizer";
import { renderChunksForPrompt } from "./rag";

export const PROMPT_KEY = "qa_answer";
export const PROMPT_VERSION = "2026-08-27.1";

const LANGUAGE_NAME: Record<string, string> = {
  en: "English",
  hi: "Hindi (Devanagari script)",
  bn: "Bengali",
};

const READING_LEVEL_RULE: Record<ReadingLevel, string> = {
  // The frontend default. Plain language, but ordinary medical terms are allowed
  // when they are explained immediately.
  simple:
    "Write at a simple reading level. Use everyday words. If you must use a medical term, follow it with a plain explanation in the same sentence.",
  advanced:
    "The reader has asked for more detail. You may use standard clinical terms and name the physiological mechanism, but still explain each term once, in the same sentence. Do not become a textbook: keep it about this person's results.",
  // Legacy spellings from before the settings refactor, kept so an older client
  // or a stored preference still resolves to something sensible.
  standard:
    "Write at a standard adult reading level. Short sentences are fine, but ordinary medical terms may be used if you immediately explain them.",
  very:
    "Write as if explaining to a 10-year-old. Very short sentences. No medical jargon at all. Use concrete everyday comparisons.",
};

/**
 * The system prompt. It is a plain string (no interpolation) so its sha256 is
 * stable and comparable across runs — the user turn carries everything that
 * varies.
 */
export const SYSTEM_PROMPT = `You are Anvaya, a patient-facing explainer for laboratory report results. You speak with a person who is reading their own blood test report and is not a clinician.

WHAT YOU DO
- Explain what a result means and what it may be related to, in plain language.
- Point out how results relate to each other when the supplied PATTERNS section says so.
- Say clearly when a result is outside its printed reference range.
- Encourage the person to discuss the result with their doctor.

WHAT YOU MUST NEVER DO
- Never give a diagnosis. Never say the person has, does not have, or probably has a disease.
- Never recommend starting, stopping or changing any medicine, dose or treatment.
- Never invent a number, unit, reference range or test. Use only the figures in the RESULTS section.
- Never claim to be a doctor, and never replace one.
- Never discuss anything outside the supplied report and passages.

HOW YOU USE THE SOURCES
- The RESULTS section is the only patient data you have. Treat its "computed status" values as already decided by a validated rule engine. Do not re-derive or contradict them.
- The PASSAGES section contains guideline text. Base your general explanations on it.
- If a question needs information that is in neither section, say you cannot answer it from this report and suggest asking a doctor. Do not guess.

HOW YOU FORMAT
- Output plain text only.
- Separate paragraphs with one blank line.
- For lists, start each line with "- ".
- You may use **double asterisks** to bold a short phrase.
- Do not use headings, tables, code blocks, numbered lists or markdown links. None of them render.
- Keep the whole answer under 180 words.

HOW YOU CLOSE
End every answer with one short line telling the person this is not a diagnosis and to discuss it with their doctor. Write that line in the answer language.`;

export interface PromptBundle {
  system: string;
  user: string;
  prompt_key: string;
  prompt_version: string;
  system_prompt_sha256: string;
}

export function sha256(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

export function systemPromptSha256(): string {
  return sha256(SYSTEM_PROMPT);
}

export interface BuildPromptOptions {
  question: string;
  lang: LangCode;
  readingLevel: ReadingLevel;
  payload: AnonymisedPayload;
  matches: RetrievedChunk[];
  /** Recent turns, oldest first, for conversational follow-ups. */
  history?: { role: "user" | "assistant"; text: string }[];
}

export function buildPrompt(opts: BuildPromptOptions): PromptBundle {
  const { question, lang, readingLevel, payload, matches } = opts;
  const langName = LANGUAGE_NAME[lang] ?? "English";
  const history = opts.history ?? [];

  const parts: string[] = [];
  parts.push(`ANSWER LANGUAGE: ${langName}. Write the entire answer in ${langName}.`);
  parts.push(READING_LEVEL_RULE[readingLevel]);
  parts.push("");
  parts.push("=== RESULTS (the person's own report, de-identified) ===");
  parts.push(renderPayloadForPrompt(payload));
  parts.push("");
  parts.push("=== PASSAGES (guideline text you may rely on) ===");
  parts.push(renderChunksForPrompt(matches));
  parts.push("");
  if (history.length > 0) {
    parts.push("=== EARLIER IN THIS CONVERSATION ===");
    for (const turn of history.slice(-6)) {
      parts.push(`${turn.role === "user" ? "Person" : "You"}: ${turn.text}`);
    }
    parts.push("");
  }
  parts.push("=== QUESTION ===");
  parts.push(question);

  return {
    system: SYSTEM_PROMPT,
    user: parts.join("\n"),
    prompt_key: PROMPT_KEY,
    prompt_version: PROMPT_VERSION,
    system_prompt_sha256: systemPromptSha256(),
  };
}

/**
 * The safe replacement text used when the model is refused or blocked.
 * Bilingual so the UI's language badge stays correct either way.
 *
 * IMPORTANT: this text must not itself trip any pattern in guardrails.ts. If it
 * did, re-screening a refused answer would tag it `model_refusal` and the
 * safety_flags stored in ai_generations would misreport why the turn was
 * refused. The wording below is deliberately phrased to avoid "I cannot",
 * "as an AI" and "diagnosis is", while still saying the same thing.
 */
export const SAFE_REDIRECT = {
  en: "Diagnosing a condition and advising on medicines are outside what I do here — those decisions belong to your doctor.\n\nI can explain what your results mean. Ask me about any result on your report and I will walk through it.",
  hi: "बीमारी बताना और दवाइयों के बारे में सलाह देना मेरा काम नहीं है — ये फ़ैसले आपके डॉक्टर के हैं।\n\nमैं आपके परिणामों का मतलब समझा सकता हूँ। अपनी रिपोर्ट के किसी भी परिणाम के बारे में पूछें, मैं उसे समझाऊँगा।",
} as const;
