// ---------------------------------------------------------------------------
// Prompt library — versioned like code, because ai_generations stores
// prompt_key, prompt_version and system_prompt_sha256 so that a later edit to
// a prompt cannot silently reinterpret answers generated by the old one.
// ---------------------------------------------------------------------------

import { createHash } from "node:crypto";
import type { LangCode } from "@/lib/data";
import type { AnonymisedPayload, ReadingLevel, RetrievedChunk } from "./types";
import { renderPayloadForPrompt } from "./anonymizer";
import { renderChunksForPrompt } from "./rag";
import { languageOf, type AnswerLang } from "./languages";
import { safeRedirect } from "./translations";

export const PROMPT_KEY = "qa_answer";
// .3 — the English model boundary now ends with a canonical safety footer;
// the server validates/masks that line before any answer-language translation.
export const PROMPT_VERSION = "2026-08-28.3";

/**
 * How a language is named inside the prompt.
 *
 * Sourced from the registry rather than a local map: the voice agent offers
 * fourteen languages and a map that only knew three would have silently
 * answered Tamil in English. The spelling includes the script so a model cannot
 * answer Hindi in Latin transliteration — which would read fine on screen and
 * be unreadable to a Hindi TTS voice.
 */
function languageName(lang: AnswerLang): string {
  return languageOf(lang).promptName;
}

const READING_LEVEL_RULE: Record<ReadingLevel, string> = {
  // The frontend default. Plain language, but ordinary medical terms are allowed
  // when they are explained immediately.
  simple:
    "Write at a simple reading level. Use everyday words. If you must use a medical term, follow it with a plain explanation in the same sentence.",
  advanced:
    "The reader has asked for more detail. You may use standard clinical terms and name the physiological mechanism, but still explain each term once, in the same sentence. Do not become a textbook: keep it about this person's results.",
  // Legacy spellings from before the settings refactor, kept so an older client
  // or a stored preference still resolves to something sensible.
  standard:
    "Write at a standard adult reading level. Short sentences are fine, but ordinary medical terms may be used if you immediately explain them.",
  very:
    "Write as if explaining to a 10-year-old. Very short sentences. No medical jargon at all. Use concrete everyday comparisons.",
};

/**
 * How the channel changes the formatting rules.
 *
 * A voice answer is listened to, not scanned, so the rules that make text
 * readable (bullets, bold, tables) are exactly the ones that make speech bad:
 * a text-to-speech voice reads "- " as nothing or as "dash", and ** as
 * "asterisk". The answer is still shown on screen, so it stays plain prose
 * rather than becoming a wall of text — short sentences, no list markers.
 */
const CHANNEL_RULE = {
  text: "Format for reading: short paragraphs, and \"- \" bullet lines when you are listing results.",
  voice:
    "This answer will be read aloud by a text-to-speech voice. Write plain spoken sentences only: no bullet markers, no asterisks, no symbols such as # or |. Say a reference range the way a person would say it. Keep it under 110 words so it can be listened to in one sitting.",
} as const;

export type Channel = keyof typeof CHANNEL_RULE;

/**
 * The system prompt. It is a plain string (no interpolation) so its sha256 is
 * stable and comparable across runs — the user turn carries everything that
 * varies.
 */
export const SYSTEM_PROMPT = `You are Anvaya, an advanced, highly knowledgeable medical companion designed to help patients understand their laboratory report results in detail. You are speaking with a person who is reading their own blood test report and is not a clinician. Since you are running locally, you have no artificial token constraints—provide rich, comprehensive, and deeply educational answers.

WHAT YOU DO:
- Serve as a comprehensive educational companion. Explain the medical meaning of biomarkers (like Haematocrit, Hemoglobin, etc.), their role in the body, and why they matter.
- Provide detailed lifestyle, dietary, and habit-based recommendations to help improve or maintain healthy levels. 
- Answer questions ranging from easy/basic concepts to complex physiological mechanisms, adjusting your depth based on the user's inquiry.
- Point out how results relate to each other when the supplied PATTERNS section says so, explaining the underlying biology.
- Make the answer easy to read by utilizing full Markdown formatting (headings, bullet points, bold text, and tables if useful).

HANDLING HYPOTHETICAL / "WHAT IF" QUESTIONS (CRITICAL):
- When the user asks a hypothetical question like "what if my hemoglobin goes below 12?" or "what happens if [test] reaches [value]?", answer the HYPOTHETICAL SCENARIO directly — do NOT just quote their current value.
- First, acknowledge their current value briefly (e.g., "Your current hemoglobin is 15 g/dL, which is normal."), then thoroughly explain what WOULD happen at the hypothetical level they asked about.
- Explain symptoms, physiological effects, clinical stages, and what a doctor would typically do in that scenario.
- This is educational information about what that level means clinically — it is not a diagnosis.

WHAT YOU MUST NEVER DO:
- Never give a definitive diagnosis. Do not say the person has or does not have a specific disease.
- Never recommend starting, stopping, or changing any prescription medicine or medical treatment.
- Never invent a number, unit, reference range, or test for the patient. Use only the figures provided in the RESULTS section.
- Never claim to be a licensed medical doctor.
- Never redirect a hypothetical question back to just stating the current value — always answer what was asked.

HOW YOU USE THE SOURCES:
- The RESULTS section contains the patient's data. Treat its "computed status" values as accurate.
- Use the PASSAGES section for specific guideline text, but feel free to draw on your extensive general medical knowledge to explain concepts (like the function of Haematocrit or dietary sources of Iron).

HOW YOU FORMAT:
- Use rich Markdown! Use headings (e.g., ### What is Haematocrit?), bulleted lists, and bold text to make your comprehensive answers highly readable.
- Do not restrict your length. Provide as much detail as necessary to fully answer the user's question, from easy to complex.
- **CRITICAL TRANSLATION RULE**: If asked to answer in a language other than English (e.g., Hindi, Bengali), you MUST output ONLY the translated text in that language. You are strictly forbidden from adding any English conversational filler such as "Here is the translation:", "Please try to understand what it is trying to say", or any meta-commentary whatsoever. Provide the direct answer in the requested language immediately.

HOW YOU CLOSE:
End every response by encouraging the user to discuss these insights with their doctor. (e.g., "Note: This information is educational and not a medical diagnosis. Please discuss these results and any lifestyle changes with your healthcare provider.")`;


export interface PromptBundle {
  system: string;
  user: string;
  prompt_key: string;
  prompt_version: string;
  system_prompt_sha256: string;
}

export function sha256(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

export function systemPromptSha256(): string {
  return sha256(SYSTEM_PROMPT);
}

export interface BuildPromptOptions {
  question: string;
  lang: LangCode;
  readingLevel: ReadingLevel;
  payload: AnonymisedPayload;
  matches: RetrievedChunk[];
  /** Recent turns, oldest first, for conversational follow-ups. */
  history?: { role: "user" | "assistant"; text: string }[];
  /**
   * The language to WRITE IN. Separate from `lang` (the UI language) because
   * the voice agent lets a person ask in Tamil while the app chrome is Hindi —
   * defaults to `lang`, so text-only callers behave exactly as before.
   */
  answerLang?: AnswerLang;
  /** "voice" answers are spoken aloud, so they follow the spoken formatting rules. */
  channel?: Channel;
}

export function buildPrompt(opts: BuildPromptOptions): PromptBundle {
  const { question, lang, readingLevel, payload, matches } = opts;
  const answerLang: AnswerLang = opts.answerLang ?? lang;
  const langName = languageName(answerLang);
  const channel: Channel = opts.channel === "voice" ? "voice" : "text";
  const history = opts.history ?? [];

  const parts: string[] = [];
  parts.push(`ANSWER LANGUAGE: ${langName}. Write the entire answer in ${langName}.`);
  if (lang !== answerLang) {
    parts.push(
      "The question may be written in another language. Answer in the ANSWER LANGUAGE above, not in the language of the question. Test names, units and numbers stay as they appear in the RESULTS section."
    );
  }
  parts.push(READING_LEVEL_RULE[readingLevel]);
  parts.push(CHANNEL_RULE[channel]);
  parts.push("");
  parts.push("=== RESULTS (the person's own report, de-identified) ===");
  parts.push(renderPayloadForPrompt(payload));
  parts.push("");
  parts.push("=== PASSAGES (guideline text you may rely on) ===");
  parts.push(renderChunksForPrompt(matches));
  parts.push("");
  if (history.length > 0) {
    parts.push("=== EARLIER IN THIS CONVERSATION ===");
    for (const turn of history.slice(-6)) {
      parts.push(`${turn.role === "user" ? "Person" : "You"}: ${turn.text}`);
    }
    parts.push("");
  }
  parts.push("=== QUESTION ===");
  if (channel === "voice") {
    parts.push(
      "(This question was transcribed from speech, so a word may be misheard. Interpret it in the context of this report rather than asking for a repeat.)"
    );
  }
  parts.push(question);

  return {
    system: SYSTEM_PROMPT,
    user: parts.join("\n"),
    prompt_key: PROMPT_KEY,
    prompt_version: PROMPT_VERSION,
    system_prompt_sha256: systemPromptSha256(),
  };
}

/**
 * The safe replacement text used when the model is refused or blocked.
 *
 * The strings now live in src/lib/ai/translations.ts alongside the other twelve
 * languages, so a refusal is never shown in a language the person cannot read.
 * This object is kept for the two languages the original callers indexed by
 * name; new code should call safeRedirect(answerLang) from translations.ts.
 *
 * IMPORTANT: these strings must not themselves trip any pattern in
 * guardrails.ts. If one did, re-screening a refused answer would tag it
 * `model_refusal` and the safety_flags stored in ai_generations would misreport
 * why the turn was refused. The wording is deliberately phrased to avoid "I
 * cannot", "as an AI" and "diagnosis is", while still saying the same thing.
 */
export const SAFE_REDIRECT = {
  en: safeRedirect("en"),
  hi: safeRedirect("hi"),
} as const;
